"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import { UserButton, useUser } from "@clerk/nextjs";
import { hasAdminEmail } from "@/lib/admin-access";

const API = "";
const PILLARS = ["AI readiness", "Finance transformation", "Trusted data", "Executive decision-making"];
const NAV = ["Post", "Spark", "Calendar", "Ideas", "Analytics"];
const PLATFORM_FORMATS = {
  LinkedIn: ["Standard post", "Event", "Celebrate", "Hiring", "Poll", "Document", "Find an expert"],
  Instagram: ["Feed post", "Carousel", "Reel"],
  Facebook: ["Feed post", "Photo", "Video", "Reel"],
  X: ["Post", "Thread"],
};
const PLATFORM_LIMITS = {LinkedIn:3000,Instagram:2200,Facebook:63206,X:280};
const BRAND_DEFAULTS={brandFocus:"Become a recognized AI subject-matter expert and launch a new AI advisory business.",tagline:"Professional thought leadership for trusted transformation.",brandPromise:"Turn relevant signals into clear, credible content that leaders trust.",voice:"Authoritative, practical, optimistic, and direct.",audience:"Finance, data, technology, and transformation leaders.",pillars:"AI readiness · Finance transformation · Trusted data · Executive decision-making",personality:"Experienced guide · Clear thinker · Constructive challenger",useOften:"Practical outcomes · Trusted insight · Measurable impact · Confident action",avoid:"Hype · Fear-based claims · Unexplained jargon · Generic inspiration",signalTeal:"#0097B2",actionRed:"#EF2923",editorialInk:"#101820"};
const seed = [
  {id:1,date:"2026-07-20",title:"Why AI readiness starts with trusted data",summary:"AI pilots fail when data cannot be trusted. Here is the foundation I help organizations build.",pillar:"AI readiness",stage:"Review",hook:"AI readiness does not begin with a model. It begins with data leaders can trust.",body:"The organizations moving fastest with AI are not skipping governance. They are investing in it.\n\nA trusted data foundation means shared definitions, clear ownership, reliable pipelines, and controls that make quality visible.",closing:"Where is the biggest trust gap in your organization’s data today?"},
  {id:2,date:"2026-07-22",title:"From five days to three hours: redesigning executive reporting",summary:"How we cut monthly reporting from five days to under three hours—and what it unlocked.",pillar:"Finance transformation",stage:"Draft",hook:"We cut monthly executive reporting from five days to under three hours. Here is what changed.",body:"The breakthrough was not a new tool—it was a new design.\n\nWe standardized data definitions, automated collection and validation, and rebuilt the report layer around clarity and decision value.",closing:"What is one report your team could redesign this quarter?"},
  {id:3,date:"2026-07-24",title:"The hidden cost of KPI disagreement",summary:"When KPIs do not agree, decisions slow down.",pillar:"Trusted data",stage:"Idea",hook:"",body:"",closing:""},
  {id:4,date:"2026-07-27",title:"What Finance should ask before automating a process",summary:"Automation without the right questions just automates waste.",pillar:"Finance transformation",stage:"Idea",hook:"",body:"",closing:""},
  {id:5,date:"2026-07-29",title:"Data integrity is not a tech problem—it is a leadership decision",summary:"How strong data governance drives better insight and builds executive trust.",pillar:"Trusted data",stage:"Review",hook:"",body:"",closing:""},
  {id:6,date:"2026-07-31",title:"From insight to action: the executive reporting chain",summary:"A simple model to connect data, insight, decision and outcome.",pillar:"Executive decision-making",stage:"Draft",hook:"",body:"",closing:""},
  {id:7,date:"2026-08-03",title:"Three questions every CFO should ask about AI",summary:"A short checklist to separate signal from noise in AI initiatives.",pillar:"AI readiness",stage:"Approved",hook:"Before approving another AI pilot, ask three questions.",body:"Is the underlying data trusted? Is the business decision clear? Is there an accountable owner for the outcome?",closing:"Which question is most often missing from the conversation?"}
];
const previewSeed = [
  {id:101,date:"2026-07-28",time:"09:00",title:"Market update: Q3 outlook",summary:"Quarterly market perspective.",pillar:"Finance transformation",stage:"Draft",hook:"",body:"",closing:""},
  {id:102,date:"2026-07-30",time:"10:00",title:"5 AI trends reshaping finance",summary:"Five practical shifts finance leaders should watch.",pillar:"AI readiness",stage:"Scheduled",hook:"",body:"",closing:""},
  {id:103,date:"2026-08-01",time:"10:00",title:"5 AI trends reshaping finance",summary:"Five practical shifts finance leaders should watch.",pillar:"AI readiness",stage:"Scheduled",hook:"",body:"",closing:""},
  {id:104,date:"2026-08-03",time:"08:30",title:"Leadership in the AI era",summary:"A practical leadership perspective.",pillar:"AI readiness",stage:"Scheduled",hook:"",body:"",closing:""},
  {id:105,date:"2026-08-05",time:"11:00",title:"Why data governance matters",summary:"Trust starts with clear ownership.",pillar:"Trusted data",stage:"Draft",hook:"",body:"",closing:""},
  {id:106,date:"2026-08-07",time:"12:00",title:"From data to decisions",summary:"Turn insight into action.",pillar:"Executive decision-making",stage:"Scheduled",hook:"",body:"",closing:""},
  {id:107,date:"2026-08-10",time:"09:00",title:"Client story: Retail transformation",summary:"A transformation premise to develop.",pillar:"Finance transformation",stage:"Idea",hook:"",body:"",closing:""},
  {id:108,date:"2026-08-12",time:"09:15",title:"Building trust with data",summary:"Credibility begins with reliable definitions.",pillar:"Trusted data",stage:"Scheduled",hook:"",body:"",closing:""},
  {id:109,date:"2026-08-17",time:"09:00",title:"Preparing your team for AI adoption",summary:"A practical readiness checklist.",pillar:"AI readiness",stage:"Draft",hook:"",body:"",closing:""},
  {id:110,date:"2026-08-20",time:"09:00",title:"Industry benchmarks 2026",summary:"Evidence to shape the next post.",pillar:"Executive decision-making",stage:"Idea",hook:"",body:"",closing:""},
  {id:111,date:"2026-08-21",time:"08:00",title:"The future of finance leaders",summary:"How the role is evolving.",pillar:"Finance transformation",stage:"Scheduled",hook:"",body:"",closing:""},
  {id:112,date:"2026-08-25",time:"09:00",title:"CFO priorities in 2026",summary:"A concise executive agenda.",pillar:"Finance transformation",stage:"Draft",hook:"",body:"",closing:""},
];
const pulseSeed = [
  {id:"onn-1",source:"McKinsey & Company",headline:"The finance function in the age of AI: From insight to impact",summary:"Leading CFOs are redesigning finance around real-time intelligence, scenario planning, and automated decision support to drive enterprise value.",topic:"Finance & Strategy",trend:"up",change:"Trending up",readTime:6,image:"/spark-lead.png"},
  {id:"onn-2",source:"Harvard Business Review",headline:"The data advantage: Building trust in an AI-driven enterprise",summary:"Poor data quality and governance remain the leading barriers to scaling AI and automation across the enterprise.",topic:"Data Management",trend:"up",change:"Up 8%",changeDetail:"vs last 7 days",readTime:5,image:"/spark-data.png"},
  {id:"onn-3",source:"MIT Sloan Management Review",headline:"Beyond automation: How AI unlocks new models of growth",summary:"From reconciliations to reporting, finance teams are finding measurable time savings without sacrificing control.",topic:"AI & Innovation",trend:"down",change:"Down 3%",changeDetail:"vs last 7 days",readTime:4,image:"/spark-geometry.png"},
  {id:"onn-4",headline:"New privacy rules raise the stakes for finance data",summary:"Upcoming regulations will require stricter controls over how financial data is collected, stored, and shared.",topic:"Trusted data",trend:"flat",potential:"Medium",readTime:4},
  {id:"onn-5",headline:"How leading CFOs are building influence beyond the numbers",summary:"Finance leaders are using trusted insight to shape strategy, drive value, and earn a stronger seat at the table.",topic:"Executive decision-making",trend:"up",potential:"High",readTime:7},
  {id:"onn-6",headline:"The cloud cost dilemma: spend smarter, not just less",summary:"Organizations are shifting from blunt cost reduction to clearer ownership, visibility, and outcome-based cloud investment.",topic:"AI readiness",trend:"down",potential:"Medium",readTime:5}
];
const count = (value="") => [...value].length;
const postText = p => [p.title,p.hook,p.body,p.closing].filter(Boolean).join("\n\n");
const formatDate = d => new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));
const formatTime = time => new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(`2000-01-01T${time||"09:00"}:00`));
const localTimezone = () => Intl.DateTimeFormat().resolvedOptions().timeZone || "America/New_York";
const savedBrand = () => {
  try { return {...BRAND_DEFAULTS,...JSON.parse(localStorage.getItem("posting-signal-brand")||"{}")}; }
  catch { return BRAND_DEFAULTS; }
};
const articlePerspective = (article,brand=savedBrand()) => {
  const sourceName=article.source||"the source publication",headline=article.headline||"This development",summary=article.summary||"",signal=`${headline} ${summary}`.toLowerCase();
  let angle={title:"The signal matters less than the decision it changes",hook:"A news headline becomes useful only when it changes what a leader does next.",point:"My read: the practical opportunity is to turn this development into a clear decision, an accountable owner, and an outcome the organization can measure.",question:"What decision should leaders revisit because of this development?"};
  if(/secrecy|secret|transparen|vet|dangerous ai|safety/.test(signal)) angle={title:"AI governance needs visible standards—not quiet assurances",hook:"If leaders cannot see how high-risk AI is evaluated, they cannot confidently govern how it is used.",point:"My perspective: confidentiality may protect parts of an evaluation process, but it cannot replace clear standards, accountable ownership, and evidence that decision-makers can challenge. Trust in AI is built when leaders can explain what was tested, who accepted the risk, and what happens when the evidence changes.",question:"What evidence would your leadership team require before approving a high-risk AI use case?"};
  else if(/data|quality|governance|trust/.test(signal)) angle={title:"AI readiness is ultimately a trust decision",hook:"The fastest AI program is still slow if leaders do not trust the data beneath it.",point:"My perspective: data quality is not a cleanup task to delegate after strategy is set. It is a leadership decision about definitions, ownership, controls, and the evidence required to act with confidence.",question:"Where would stronger data ownership remove the most decision friction in your organization?"};
  else if(/finance|cfo|reporting|cost/.test(signal)) angle={title:"Finance transformation should shorten the distance to a decision",hook:"A faster finance process matters only when it helps leaders make a better decision sooner.",point:"My perspective: the real measure of finance transformation is not automation alone. It is whether trusted information reaches the right owner soon enough to change an outcome.",question:"Which finance decision would create the most value if its cycle time were cut in half?"};
  else if(/leadership|leader|board|executive/.test(signal)) angle={title:"Leadership advantage comes from turning signals into choices",hook:"Leaders do not need more signals. They need a clearer way to decide what those signals demand.",point:"My perspective: strong leadership converts uncertainty into an explicit choice, a named owner, and a learning loop. That discipline matters more than sounding certain too early.",question:"What choice does this signal put in front of your leadership team?"};
  const focus=brand.brandFocus?.trim(),voice=brand.voice?.trim(),promise=brand.brandPromise?.trim();
  const reported=(summary.replace(/[.!?]+$/," ").trim()||headline).replace(/^./,character=>character.toLowerCase());
  return {date:new Date().toISOString().slice(0,10),time:"09:00",timezone:localTimezone(),title:angle.title,summary:`An original ${brand.personality?.split(/[·,]/)[0]?.trim().toLowerCase()||"leadership"} perspective inspired by ${sourceName}.`,pillar:article.topic||PILLARS[0],stage:"Draft",hook:angle.hook,body:`${sourceName} reports that ${reported}.\n\n${angle.point}${focus?`\n\nThat connects directly to my focus: ${focus.replace(/[.!?]+$/," ").trim()}.`:""}${promise?` The standard I keep coming back to is simple: ${promise.charAt(0).toLowerCase()}${promise.slice(1)}`:""}`,closing:angle.question,sourceArticleId:article.id,source:sourceName,sourceReference:{headline,url:article.url||"",publisher:sourceName,publishedAt:article.publishedAt||null},perspectiveProfile:{brandFocus:focus||"",voice:voice||"",generatedFromBrand:true}};
};
const needsPerspectiveRepair = (draft,article) => {
  const headline=(article.headline||"").trim().toLowerCase(),title=(draft.title||"").trim().toLowerCase(),hook=(draft.hook||"").trim().toLowerCase();
  return title===headline||hook===headline||title===`a perspective on ${headline}`||draft.closing==="What is your perspective?"||draft.closing==="What perspective would you add to this conversation?";
};
const postPayload = post => {
  const {id,title,summary,hook,body,closing,pillar,stage,date,time,timezone,publishingJob,scheduledFor,createdAt,updatedAt,publishedAt,linkedinPostId,...content}=post;
  return {title:title||"Untitled post",summary:summary||"",hook:hook||"",body:body||"",closing:closing||"",pillar:pillar||PILLARS[0],stage:stage||"Idea",date,time:time||"09:00",timezone:timezone||localTimezone(),content};
};
const scheduledInstant = post => new Date(`${post.date}T${post.time||"09:00"}:00`).toISOString();

export default function PostingSignalApp({previewMode=false}){
  const [posts,setPosts]=useState(seed),[hydrated,setHydrated]=useState(false);
  const [active,setActive]=useState("Spark"),[selected,setSelected]=useState(2),[editing,setEditing]=useState(false),[toast,setToast]=useState(""),[mediaOpen,setMediaOpen]=useState(false),[savedArticles,setSavedArticles]=useState([]),[hiddenArticles,setHiddenArticles]=useState([]),[articlePreferences,setArticlePreferences]=useState([]),[shareArticle,setShareArticle]=useState(null),[railOpen,setRailOpen]=useState(true),[railDate,setRailDate]=useState(()=>new Date().toISOString().slice(0,10));
  const landingResolvedRef=useRef(false);
  useEffect(()=>{if(window.matchMedia("(max-width: 900px)").matches)setRailOpen(false)},[]);
  useEffect(()=>{if(!previewMode||!hydrated)return;const query=new URLSearchParams(location.search),previewPage=query.get("page");if(NAV.includes(previewPage)){landingResolvedRef.current=true;setActive(previewPage)}if(query.get("view")!=="editor")return;landingResolvedRef.current=true;setActive("Post");setEditing(true);const previewPlatform=query.get("platform");if(PLATFORM_FORMATS[previewPlatform])setPosts(all=>all.map((item,index)=>index===0?{...item,platform:previewPlatform,type:PLATFORM_FORMATS[previewPlatform][0]}:item))},[previewMode,hydrated]);
  useEffect(()=>{const controller=new AbortController();const load=async()=>{let localPosts=seed;try{localPosts=JSON.parse(localStorage.getItem("signal-posts"))||seed}catch{}if(previewMode){setPosts(localPosts);setSelected(localPosts[0]?.id||null);setSavedArticles(localPosts.filter(post=>post.sourceArticleId&&post.stage==="Idea").map(post=>post.sourceArticleId));setHydrated(true);return}try{const response=await fetch("/api/posts",{signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||"Posts could not be loaded");let durablePosts=data.posts||[];if(!durablePosts.length&&localPosts.length){const imported=await fetch("/api/posts/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({posts:localPosts})});const importedData=await imported.json();if(imported.ok)durablePosts=importedData.posts||[]}const next=durablePosts.length?durablePosts:localPosts;setPosts(next);setSelected(next[0]?.id||null);setSavedArticles(next.filter(post=>post.sourceArticleId&&post.stage==="Idea").map(post=>post.sourceArticleId))}catch(error){if(!controller.signal.aborted){setPosts(localPosts);setToast(error instanceof Error?error.message:"Using browser posts until the database is available")}}finally{if(!controller.signal.aborted)setHydrated(true)}};load();return()=>controller.abort()},[previewMode]);
  useEffect(()=>{if(!previewMode||!hydrated)return;setPosts(previewSeed);setSelected(previewSeed[0]?.id||null);setSavedArticles([])},[previewMode,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem("signal-posts",JSON.stringify(posts))},[posts,hydrated]);
  useEffect(()=>{if(!hydrated)return;const load=async()=>{if(previewMode){let items=[];try{items=JSON.parse(localStorage.getItem("signal-article-preferences"))||[]}catch{}setArticlePreferences(items);setSavedArticles(items.filter(item=>item.saved).map(item=>item.articleId));setHiddenArticles(items.filter(item=>item.hidden).map(item=>item.articleId));return}try{const response=await fetch("/api/articles");const data=await response.json();if(!response.ok)throw Error(data.error||"Article library could not be loaded");const items=data.items||[];setArticlePreferences(items);setSavedArticles(items.filter(item=>item.saved).map(item=>item.articleId));setHiddenArticles(items.filter(item=>item.hidden).map(item=>item.articleId))}catch(error){notify(error instanceof Error?error.message:"Article library could not be loaded")}};load()},[hydrated,previewMode]);
  useEffect(()=>{if(!hydrated||landingResolvedRef.current)return;const today=new Date().toISOString().slice(0,10),todayPosts=posts.filter(item=>item.date===today&&["Scheduled","Draft","Review","Idea"].includes(item.stage));landingResolvedRef.current=true;if(todayPosts.length){setActive("Post");setSelected(todayPosts[0].id)}else setActive("Spark")},[hydrated,posts]);
  const post=posts.find(p=>p.id===selected)||posts[0];
  const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)};
  const patch=(key,value)=>setPosts(all=>all.map(p=>p.id===selected?{...p,[key]:value}:p));
  const savePost=async next=>{const response=await fetch(`/api/posts/${next.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(next))});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be saved");setPosts(all=>all.map(item=>item.id===next.id?data.post:item));return data.post};
  const schedulePost=async next=>{const response=await fetch(`/api/posts/${next.id}/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scheduledFor:scheduledInstant(next),date:next.date,time:next.time||"09:00",timezone:next.timezone||localTimezone()})});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be scheduled");setPosts(all=>all.map(item=>item.id===next.id?data.post:item));return data.post};
  const movePost=async(id,date)=>{const current=posts.find(item=>item.id===id);if(!current)return;const next={...current,date,updatedAt:new Date().toISOString()};setPosts(all=>all.map(item=>item.id===id?next:item));try{if(current.stage==="Scheduled")await schedulePost(next);else await savePost(next);notify(`Post moved to ${formatDate(date)}`)}catch(error){notify(error instanceof Error?error.message:"Post could not be moved")}};
  const openPost=id=>{setSelected(id);if(active==="Calendar")setActive("Post");setEditing(true);window.scrollTo({top:0,behavior:"smooth"})};
  const persistArticlePreference=async(article,changes)=>{const current=articlePreferences.find(item=>item.articleId===article.id)||{articleId:article.id,article,saved:false,hidden:false};const next={...current,...changes,article};const items=[next,...articlePreferences.filter(item=>item.articleId!==article.id)];setArticlePreferences(items);setSavedArticles(items.filter(item=>item.saved).map(item=>item.articleId));setHiddenArticles(items.filter(item=>item.hidden).map(item=>item.articleId));if(previewMode){localStorage.setItem("signal-article-preferences",JSON.stringify(items));return next}const response=await fetch("/api/articles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({article,...changes})});const data=await response.json();if(!response.ok)throw Error(data.error||"Article preference could not be saved");setArticlePreferences(all=>[data.item,...all.filter(item=>item.articleId!==article.id)]);return data.item};
  const saveArticle=async article=>{const saved=savedArticles.includes(article.id);try{await persistArticlePreference(article,{saved:!saved});notify(saved?"Removed from Library":"Saved to Library")}catch(error){notify(error instanceof Error?error.message:"Article could not be saved")}};
  const voteArticle=async(article,vote)=>{const current=articlePreferences.find(item=>item.articleId===article.id)?.vote||null,next=current===vote?null:vote;try{await persistArticlePreference(article,{vote:next});notify(next===null?"Article vote cleared":next==="up"?"Article up voted":"Article down voted")}catch(error){notify(error instanceof Error?error.message:"Article vote could not be saved")}};
  const draftArticle=async article=>{let draft=posts.find(item=>item.sourceArticleId===article.id&&["Draft","Review"].includes(item.stage)),next=articlePerspective(article);if(draft&&needsPerspectiveRepair(draft,article)){const repaired={...draft,...next,id:draft.id,stage:draft.stage};if(previewMode){draft=repaired;setPosts(all=>all.map(item=>item.id===draft.id?draft:item))}else try{draft=await savePost(repaired);notify("Draft rewritten in your Brand voice")}catch(error){notify(error instanceof Error?error.message:"Draft could not be rewritten");return}}else if(!draft){if(previewMode){draft={...next,id:`preview-${Date.now()}`};setPosts(all=>[draft,...all])}else try{const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(next))});const data=await response.json();if(!response.ok)throw Error(data.error||"Draft could not be created");draft=data.post;setPosts(all=>[draft,...all])}catch(error){notify(error instanceof Error?error.message:"Draft could not be created");return}}setSelected(draft.id);setActive("Ideas");setEditing(true)};
  const shareArticleNow=async article=>{if(previewMode){notify("Article share preview confirmed");setShareArticle(null);return}try{const response=await fetch("/api/linkedin/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:article.url||article.headline,idempotencyKey:`article-share-${article.id}-${Date.now()}`})});const data=await response.json();if(!response.ok)throw Error(data.error||"Article could not be shared");notify("Article shared to LinkedIn");setShareArticle(null)}catch(error){notify(error instanceof Error?error.message:"Article could not be shared")}};
  const create=async(stage="Idea",date=new Date().toISOString().slice(0,10))=>{const draft={date,time:"09:00",timezone:localTimezone(),title:stage==="Idea"?"Untitled idea":"Untitled post",summary:"Add a short premise.",pillar:PILLARS[0],stage,hook:"",body:"",closing:""};try{const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(draft))});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be created");setPosts(v=>[data.post,...v]);setSelected(data.post.id);setEditing(true)}catch(error){notify(error instanceof Error?error.message:"Post could not be created")}};
  const saveStage=async(stage,message)=>{const next={...post,stage,updatedAt:new Date().toISOString()};setPosts(all=>all.map(item=>item.id===selected?next:item));try{await savePost(next);notify(message)}catch(error){notify(error instanceof Error?error.message:"Post could not be saved")}};
  const saveField=async(key,value)=>{const next={...post,[key]:value,updatedAt:new Date().toISOString()};setPosts(all=>all.map(item=>item.id===selected?next:item));if(previewMode)return;try{await savePost(next)}catch(error){notify(error instanceof Error?error.message:"Post could not be saved")}};
  const approve=async()=>{const next={...post,stage:"Scheduled",time:post.time||"09:00",timezone:post.timezone||localTimezone()};try{await savePost({...next,stage:"Approved"});await schedulePost(next);notify(`Approved and scheduled for ${formatDate(next.date)} at ${next.time}`)}catch(error){notify(error instanceof Error?error.message:"Post could not be scheduled")}};
  const remove=async()=>{if(!confirm(`Delete “${post.title}”? This cannot be undone.`))return;try{const response=await fetch(`/api/posts/${post.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be deleted");setPosts(v=>v.filter(p=>p.id!==selected));setEditing(false);notify("Post deleted")}catch(error){notify(error instanceof Error?error.message:"Post could not be deleted")}};
  const postNow=async()=>{if(!confirm(`Publish “${post.title}” to your connected LinkedIn account now?`))return;try{const response=await fetch("/api/linkedin/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:postText(post),idempotencyKey:`post-${post.id}-${post.updatedAt||post.date}`})});const data=await response.json();if(!response.ok)throw Error(data.error||"LinkedIn publishing failed");const next={...post,stage:"Published",publishedAt:new Date().toISOString(),linkedinPostId:data.platformPostId};setPosts(all=>all.map(item=>item.id===post.id?next:item));await savePost(next);notify("Published to LinkedIn")}catch(error){notify(error instanceof Error?error.message:"LinkedIn publishing failed")}};
  const openCanva=async()=>{const popup=window.open("about:blank","posting-signal-canva");try{const response=await fetch(`${API}/api/canva/launch`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({postId:post.id,title:post.title,imageUrl:post.media?.url})});const data=await response.json();if(!response.ok)throw Error(data.error||"Canva could not start");popup.location=data.launchUrl}catch(error){popup?.close();notify(error.message)}};
  useEffect(()=>{const q=new URLSearchParams(location.search),designId=q.get("canvaDesignId"),postId=q.get("canvaPostId");if(!designId||!postId)return;fetch(`${API}/api/canva/export`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({designId,postId})}).then(r=>r.json()).then(data=>setPosts(all=>all.map(p=>String(p.id)===postId?{...p,media:{url:data.url,alt:`Canva design for ${p.title}`,source:"Canva",designId}}:p))).finally(()=>history.replaceState({},"",location.pathname))},[]);
  const composer=editing&&post?<Composer post={post} patch={patch} commitField={saveField} standalone back={()=>setEditing(false)} browse={()=>setMediaOpen(true)} canva={openCanva} saveIdea={()=>saveStage("Idea","Idea saved")} saveDraft={()=>saveStage("Draft","Draft saved")} approve={approve} remove={remove} postNow={postNow} notify={notify}/>:null;
  const deleteItem=async item=>{if(!confirm(`Delete “${item.title}”? This cannot be undone.`))return;if(item.isLibraryArticle){try{await persistArticlePreference(item.article,{saved:false});notify("Article removed from Library")}catch(error){notify(error instanceof Error?error.message:"Article could not be removed")}return}if(previewMode){setPosts(all=>all.filter(post=>post.id!==item.id));notify(`${item.stage} deleted`);return}try{const response=await fetch(`/api/posts/${item.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw Error(data.error||"Item could not be deleted");setPosts(all=>all.filter(post=>post.id!==item.id));notify(`${item.stage} deleted`)}catch(error){notify(error instanceof Error?error.message:"Item could not be deleted")}};
  const libraryArticles=articlePreferences.filter(item=>item.saved).map(item=>({id:`article-${item.articleId}`,title:item.article.headline,summary:item.article.summary,pillar:item.article.topic,stage:"Library",source:item.article.source,url:item.article.url,image:item.article.image,sourceArticleId:item.articleId,isLibraryArticle:true,article:item.article}));
  const articleVotes=Object.fromEntries(articlePreferences.filter(item=>item.vote).map(item=>[item.articleId,item.vote]));
  const content=editing?composer:active==="Spark"?<Pulse articles={pulseSeed.filter(article=>!hiddenArticles.includes(article.id))} saved={savedArticles} votes={articleVotes} onVote={voteArticle} onSave={saveArticle} onDraft={draftArticle} onShare={setShareArticle} onHide={article=>persistArticlePreference(article,{hidden:true}).then(()=>notify("Article hidden")).catch(error=>notify(error.message))} notify={notify}/>:active==="Post"?<TodaysPosts posts={posts} open={openPost} create={create}/>:active==="Analytics"?<Analytics posts={posts}/>:<Workspace active={active} posts={posts} libraryArticles={libraryArticles} open={openPost} create={create} removeItem={deleteItem} movePost={movePost} onSelectDay={date=>{setRailDate(date);setRailOpen(true)}} previewMode={previewMode}/>;
  return <div className={`shell${railOpen?" today-rail-open":""}`}>
    <Sidebar active={active} previewMode={previewMode} onNav={n=>{setActive(n);setEditing(false);window.scrollTo({top:0,behavior:"smooth"})}} notify={notify}/>
    <main className={editing&&active!=="Calendar"?"editing":""}>
      <span className="page-post-mark" aria-hidden="true"/>
      {content}
      {toast?<div className="toast">{toast}</div>:null}
    </main>
    {railOpen?<TodayRail date={railDate} posts={posts} open={openPost} create={create} close={()=>setRailOpen(false)}/>:<button className="today-rail-reopen" type="button" onClick={()=>setRailOpen(true)} aria-label="Open today rail"><Icon name="Calendar" size={20}/></button>}
    {mediaOpen&&post?<MediaPicker post={post} choose={m=>{patch("media",m);setMediaOpen(false);notify("Image added")}} close={()=>setMediaOpen(false)} canva={openCanva}/>:null}
    {shareArticle?<ShareArticleDialog article={shareArticle} close={()=>setShareArticle(null)} confirm={()=>shareArticleNow(shareArticle)}/>:null}
  </div>
}

function Icon({name,size=20}){const paths={Home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/></>,Pulse:<><path d="M3 12h3l2.1-6 3.3 12 2.4-7 1.7 3H21"/></>,Calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/></>,Clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,Ideas:<path d="M12 3 21 12 12 21 3 12Z"/>,Drafts:<><path d="m4 20 4.5-1 10.8-10.8a2.1 2.1 0 0 0-3-3L5.5 16Z"/><path d="m14.8 6.7 3 3"/></>,Library:<><rect x="5" y="5" width="15" height="16" rx="1"/><path d="M3 18V4a1 1 0 0 1 1-1h13"/></>,Trash:<><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/></>,Analytics:<><path d="M4 20v-7h4v7M10 20V8h4v12M16 20V3h4v17"/></>,Bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,Settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/></>,More:<><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></>,Save:<path d="M6 3h12a1 1 0 0 1 1 1v17l-7-4-7 4V4a1 1 0 0 1 1-1Z"/>,Source:<><path d="M14 3h7v7M10 14 21 3"/><path d="M21 14v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h6"/></>,Share:<><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></>,VoteUp:<path d="M2 10h4v11H2V10Zm6 0 4-8c1.9 0 3.2 1.7 2.6 3.5L13.8 8h5.6a2.5 2.5 0 0 1 2.4 3.1l-1.9 7.3a2.2 2.2 0 0 1-2.2 1.6H8V10Z" fill="currentColor" stroke="none"/>,VoteDown:<path d="M2 3h4v11H2V3Zm6 1h9.7a2.2 2.2 0 0 1 2.2 1.6l1.9 7.3a2.5 2.5 0 0 1-2.4 3.1h-5.6l.8 2.5c.6 1.8-.7 3.5-2.6 3.5l-4-8V4Z" fill="currentColor" stroke="none"/>,Hide:<><path d="M1.8 12S5.5 5 12 5s10.2 7 10.2 7S18.5 19 12 19 1.8 12 1.8 12Zm10.2 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z" fill="currentColor" fillRule="evenodd" stroke="none"/><path d="M4 4 20 20" stroke="currentColor" strokeWidth="3.2"/></>};return <svg className="ui-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

function Sidebar({active,onNav,notify,previewMode=false}){
  const navIcon=name=>name==="Post"?"Home":name==="Spark"?"Pulse":name;
  const {user}=useUser(),isAdmin=hasAdminEmail(user?.emailAddresses);
  return <><header className="app-topbar"><div className="brand"><img className="post-logo-mark" src="/brand/post-icon-red.png" alt=""/>PostingSignal</div><div className="topbar-utilities"><button type="button" aria-label="Notifications"><Icon name="Bell" size={21}/></button>{previewMode?<span className="preview-avatar" aria-label="Preview user">RW</span>:<UserButton><UserButton.MenuItems><UserButton.Action label="manageAccount"/>{isAdmin?<UserButton.Link label="Admin" href="/admin" labelIcon={<Icon name="Settings" size={14}/>}/>:null}<UserButton.Action label="signOut"/></UserButton.MenuItems><UserButton.UserProfilePage label="account"/><UserButton.UserProfilePage label="Brand" url="brand" labelIcon={<Icon name="Ideas" size={14}/>}><BrandSettings/></UserButton.UserProfilePage><UserButton.UserProfilePage label="Integrations" url="integrations" labelIcon={<Icon name="Settings" size={14}/>}><Settings notify={notify}/></UserButton.UserProfilePage><UserButton.UserProfilePage label="security"/></UserButton>}</div></header><nav className="nav-carousel" aria-label="Primary navigation"><div className="nav-carousel-track">{NAV.map(name=><button type="button" key={name} className={active===name?"active":""} onClick={()=>onNav(name)} aria-label={name} aria-current={active===name?"page":undefined} title={name}><Icon name={navIcon(name)} size={active===name?30:25}/><span className="sr-only">{name}</span></button>)}</div></nav></>
}

function TodaysPosts({posts,open,create}){
  const today=new Date().toISOString().slice(0,10);
  const scheduled=posts.filter(post=>post.date===today&&post.stage==="Scheduled");
  const drafts=posts.filter(post=>post.date===today&&["Draft","Review"].includes(post.stage));
  const ideas=posts.filter(post=>post.date===today&&post.stage==="Idea");
  const groups=[
    {key:"scheduled",title:"Scheduled today",description:"Review and confirm your scheduled posts.",items:scheduled,icon:"Calendar",action:"Review post"},
    {key:"drafts",title:"Drafts to finish",description:"Pick up where you left off.",items:drafts,icon:"Drafts",action:"Continue editing"},
    {key:"ideas",title:"Ideas for today",description:"Turn ideas into trusted content.",items:ideas,icon:"Ideas",action:"Turn into post"},
  ];
  return <div className="today-page bauhaus-page"><header className="today-heading"><div><h1>Today’s Posts</h1><p>Here’s what’s scheduled, in progress, and ready to create.</p></div><div className="today-summary"><time><Icon name="Calendar" size={20}/><span>{new Date(`${today}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}<small>{new Date(`${today}T12:00:00`).toLocaleDateString("en-US",{weekday:"long"})}</small></span></time><b>{scheduled.length}<small>Scheduled</small></b><b>{drafts.length}<small>Drafts</small></b><b>{ideas.length}<small>Ideas</small></b></div></header><section className="today-groups">{groups.map(group=><article className={`today-group ${group.key}`} key={group.key}><header><span><Icon name={group.icon} size={24}/></span><div><h2>{group.title}</h2><p>{group.description}</p></div><b>{group.items.length}</b></header><div className="today-items">{group.items.length?group.items.map(post=><button key={post.id} onClick={()=>open(post.id)}><div><small>{post.stage}{post.time?` · ${formatTime(post.time)}`:""}</small><h3>{post.title}</h3><p>{post.summary||post.pillar}</p></div><span>{group.action}　→</span></button>):<div className="today-empty"><Icon name={group.icon} size={28}/><p>Nothing here for today.</p></div>}</div></article>)}</section><footer className="today-footer"><span>✓</span> Your plan stays focused on what needs attention today.</footer></div>
}

function TodayRail({date,posts,open,create,close}){
  const today=date,todayDate=new Date(`${today}T12:00:00`),todayPosts=posts.filter(post=>post.date===today),upcoming=posts.filter(post=>post.date>today&&post.stage==="Scheduled").sort((a,b)=>`${a.date}${a.time||""}`.localeCompare(`${b.date}${b.time||""}`)).slice(0,3),drafts=posts.filter(post=>post.date!==today&&["Draft","Review"].includes(post.stage)).slice(0,3),ideas=posts.filter(post=>post.date!==today&&post.stage==="Idea").slice(0,3);
  const groups=[{title:"Today’s posts",items:todayPosts,empty:"No posts for today"},{title:"Upcoming",items:upcoming,empty:"No upcoming posts"},{title:"Drafts",items:drafts,empty:"No other drafts"},{title:"Ideas",items:ideas,empty:"No other ideas"}];
  return <aside className="shared-today-rail" aria-label="Today’s posting plan"><header><h2>{todayDate.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</h2><button type="button" aria-label="Close today rail" onClick={close}>×</button></header><button className="primary day-new" type="button" onClick={()=>create("Idea",today)}>＋　Create post</button><div className="day-pane-groups">{groups.map(group=><section key={group.title}><h3>{group.title} <b>{group.items.length}</b></h3>{group.items.length?group.items.map(post=><button type="button" key={post.id} className={post.stage.toLowerCase()} onClick={()=>open(post.id)}><small><b>in</b> {post.stage}{post.time?` · ${formatTime(post.time)}`:""}</small><strong>{post.title}</strong><span>●　{post.stage==="Scheduled"?"On schedule":post.pillar}</span></button>):<p>{group.empty}</p>}</section>)}</div><footer><i className="scheduled"/>Scheduled <i className="draft"/>Draft <i className="idea"/>Idea <i className="published"/>Published</footer></aside>
}

function Workspace({active,posts,libraryArticles=[],open,create,removeItem,movePost,onSelectDay,previewMode=false}){
  const [ideaFilter,setIdeaFilter]=useState("All"),[ideaQuery,setIdeaQuery]=useState("");
  const copy={Calendar:["Content Calendar","Plan, organize, and publish content that drives impact."],Ideas:["Ideas","Develop ideas, continue drafts, and reuse completed content."]}[active];
  const contentItems=[...posts,...libraryArticles];
  const shown=active!=="Ideas"?posts:contentItems.filter(post=>{const matchesFilter=ideaFilter==="All"||ideaFilter==="Ideas"&&post.stage==="Idea"||ideaFilter==="Drafts"&&["Draft","Review"].includes(post.stage)||ideaFilter==="Library"&&post.isLibraryArticle;const haystack=`${post.title} ${post.summary} ${post.pillar} ${post.source||""}`.toLowerCase();return matchesFilter&&haystack.includes(ideaQuery.trim().toLowerCase())});
  return <div className={`workspace bauhaus-page${active==="Calendar"?" calendar-workspace":" ideas-workspace"}`}><header><div><h1>{copy[0]}</h1><p>{copy[1]}</p></div></header>
  {active==="Calendar"?<PostingCalendar posts={posts} open={open} create={create} movePost={movePost} onSelectDay={onSelectDay}/>:<><div className="idea-tools"><nav aria-label="Filter ideas">{["All","Ideas","Drafts","Library"].map(filter=><button className={ideaFilter===filter?"active":""} aria-pressed={ideaFilter===filter} onClick={()=>setIdeaFilter(filter)} key={filter}>{filter}</button>)}</nav><label><span className="sr-only">Search ideas</span><input type="search" value={ideaQuery} onChange={event=>setIdeaQuery(event.target.value)} placeholder="Search ideas, signals, and documents"/></label></div><section className="idea-grid">{shown.map(p=><article key={p.id} className="idea-card"><button className="idea-card-open" onClick={()=>p.isLibraryArticle?p.url&&window.open(p.url,"_blank","noopener,noreferrer"):open(p.id)}><span className="card-post-mark" aria-hidden="true"/><header><span>{p.isLibraryArticle?"Saved article":p.source?"Spark signal":p.stage}</span><Icon name={p.stage==="Idea"?"Ideas":["Draft","Review"].includes(p.stage)?"Drafts":"Library"} size={18}/></header><h2>{p.title}</h2><p>{p.publishingJob?.lastError||p.summary}</p>{p.stage==="Draft"?<i><b style={{width:"48%"}}/></i>:null}<footer><span>{p.pillar}</span>{p.date?<time>{formatDate(p.date)}</time>:null}</footer></button><button className="idea-card-delete" aria-label={`Delete ${p.title}`} title="Delete" onClick={()=>removeItem(p)}><Icon name="Trash" size={18}/></button></article>)}</section></>}
  {!shown.length?<div className="empty"><h2>No {active.toLowerCase()} yet</h2><p>Create one to get started.</p></div>:null}</div>
}

function ArticleActions({article,isSaved,vote,onVote,onSave,onDraft,onShare,onHide,notify,compact=false}){return <div className={`article-actions${compact?" compact":""}`}><button type="button" title="Open in Editor" aria-label="Open in Editor" onClick={()=>onDraft(article)}><Icon name="Drafts" size={compact?16:20}/></button><button type="button" title={isSaved?"Remove saved article":"Save article"} aria-label={isSaved?"Remove saved article":"Save article"} className={isSaved?"saved":""} aria-pressed={isSaved} onClick={()=>onSave(article)}><Icon name="Save" size={compact?16:20}/></button><button type="button" title="View source" aria-label="View source" onClick={()=>article.url?window.open(article.url,"_blank","noopener,noreferrer"):notify("Source preview unavailable for this sample signal")}><Icon name="Source" size={compact?16:20}/></button><button type="button" title="Share as post" aria-label="Share as post" onClick={()=>onShare(article)}><Icon name="Share" size={compact?16:20}/></button><button type="button" title="Up vote article" aria-label="Up vote article" className={vote==="up"?"voted-up":""} aria-pressed={vote==="up"} onClick={()=>onVote(article,"up")}><Icon name="VoteUp" size={compact?16:20}/></button><button type="button" title="Down vote article" aria-label="Down vote article" className={vote==="down"?"voted-down":""} aria-pressed={vote==="down"} onClick={()=>onVote(article,"down")}><Icon name="VoteDown" size={compact?16:20}/></button><button type="button" title="Hide" aria-label="Hide" className="hide-action" onClick={()=>onHide(article)}><Icon name="Hide" size={compact?16:20}/></button></div>}

function TrendArrow({trend}){return <span className={`trend-arrow ${trend}`} aria-hidden="true"><svg viewBox="0 0 24 24"><path d={trend==="down"?"M5 7l6 6 4-4 4 4M19 9v4h-4":"M5 17l6-6 4 4 4-4M19 15v-4h-4"}/></svg></span>}
function SignalMeta({article,lead=false}){return <div className={`article-signal${lead?" lead-signal":""}`}><TrendArrow trend={article.trend}/><b className={article.trend}><span>{article.change||`Trending ${article.trend}`}</span>{article.changeDetail?<small>{article.changeDetail}</small>:null}</b></div>}

function MagazineArticle({article,variant="card",saved,votes,onVote,onSave,onDraft,onShare,onHide,notify}){if(!article)return null;return <article className={`template-story ${variant}`}>{article.image?<img src={article.image} alt=""/>:<span className="story-image-fallback"/>}<div className="template-copy"><small>{article.topic||"Perspective"}</small><h2>{article.headline}</h2>{!variant.includes("brief")&&article.summary?<p>{article.summary}</p>:null}</div><footer><SignalMeta article={article}/><ArticleActions compact article={article} isSaved={saved.includes(article.id)} vote={votes[article.id]} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/></footer></article>}

function SparkMagazine({articles,saved,votes,onVote,onSave,onDraft,onShare,onHide,notify}){const story=(index,variant="card")=><MagazineArticle key={articles[index]?.id||index} article={articles[index]} variant={variant} saved={saved} votes={votes} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/>,featureSeed=String(articles[0]?.id||"spark").split("").reduce((sum,char)=>sum+char.charCodeAt(0),0),featurePosition=["feature-left","feature-center","feature-right"][featureSeed%3];return <section className={`spark-magazine pulse-layout-template ${featurePosition}`} aria-label="Magazine news feed"><div className="template-opening"><div className="template-feature">{story(0,"feature")}</div><div className="template-stack">{[1,2,3,4].map(index=>story(index,"stack"))}</div><aside className="template-briefs"><h2>In brief</h2>{[5,6,7,8].map(index=>story(index,"brief"))}</aside><div className="template-triplet">{[9,10,11].map(index=>story(index,"card"))}</div><div className="template-long-read">{story(12,"long-read")}<div>{[13,14,15,16].map(index=>story(index,"card"))}</div></div></div><div className="template-lower"><div className="template-reportage">{story(17,"reportage")}</div><div className="template-four-up">{[18,19,20,21].map(index=>story(index,"card"))}</div><aside className="template-picks"><h2>Editor’s picks</h2>{[22,23,24].map(index=>story(index,"brief"))}</aside><div className="template-wide-story">{story(25,"wide")}</div><div className="template-five-up">{[26,27,28,29,30].map(index=>story(index,"card"))}</div><div className="template-compact-row">{articles.slice(31).map(article=><MagazineArticle key={article.id} article={article} variant="brief" saved={saved} votes={votes} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/>)}</div></div></section>}

function Pulse({articles,saved,votes,onVote,onSave,onDraft,onShare,onHide:hideParent,notify}){
  const [topic,setTopic]=useState("All Topics"),[feed,setFeed]=useState(articles),[loading,setLoading]=useState(false);
  const refresh=async()=>{setLoading(true);try{const response=await fetch("/api/news");const data=await response.json();if(!response.ok||!data.articles?.length)throw Error(data.error||"No live signals returned");setFeed(data.articles);notify(`${data.articles.length} live signals loaded from ${data.provider}`)}catch(error){setFeed(articles);notify(error instanceof Error?`${error.message}; showing sample signals`:"Showing sample signals")}finally{setLoading(false)}};
  const onHide=article=>{setFeed(current=>current.filter(item=>item.id!==article.id));hideParent(article)};
  useEffect(()=>{refresh()},[]);
  const topics=[...new Set(feed.map(article=>article.topic))],shown=topic==="All Topics"?feed:feed.filter(article=>article.topic===topic),lead=shown[0],rest=shown.slice(1,13),adjacent=shown.slice(13);
  return <div className="pulse editorial-pulse">
    <header className="pulse-heading"><div><h1>Today’s Spark</h1><p>Curated signals on finance, data, and AI transformation.<br/>No urgent alerts—just what matters now.</p></div><div className="pulse-controls"><select aria-label="Filter Spark by topic" value={topic} onChange={event=>setTopic(event.target.value)}><option>All Topics</option>{topics.map(pillar=><option key={pillar}>{pillar}</option>)}</select><button className="refresh" disabled={loading} onClick={refresh} aria-label="Refresh Spark"><svg className="refresh-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6v5h-5M4 18v-5h5M6.1 8.5A7 7 0 0 1 18.7 7L20 11M4 13l1.3 4A7 7 0 0 0 17.9 15.5"/></svg><span>{loading?"Refreshing":"Refresh"}</span></button></div></header>
    <div className="spark-decoration" aria-hidden="true"><span className="spark-teal-shape"/><span className="spark-red-dot"/><span className="spark-dot-grid"/></div>
    {lead?<div className="spark-content"><article className="lead-story"><img className={`spark-image-${lead.imagePosition||"left"}`} src={lead.image||"/pulse-architecture.png"} alt="News article illustration"/><div className="lead-copy"><small><b>♜</b> {lead.source||"ONN"}　·　{lead.topic}</small><h2>{lead.headline}</h2><p>{lead.summary}</p><div className="lead-footer"><SignalMeta article={lead} lead/><ArticleActions article={lead} isSaved={saved.includes(lead.id)} vote={votes[lead.id]} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/></div></div></article><div className="spark-lower">{adjacent.length?<section className="spark-adjacent" aria-label="Adjacent signals">{adjacent.map(article=><article key={article.id}>{article.image?<img src={article.image} alt=""/>:<span className="story-image-fallback"/>}<h2>{article.headline}</h2><small>{article.source} · {article.topic}</small><ArticleActions compact article={article} isSaved={saved.includes(article.id)} vote={votes[article.id]} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/></article>)}</section>:null}<section className="story-index">{rest.map(article=><article className="story-row" key={article.id}>{article.image?<img className={`spark-image-${article.imagePosition||"center"}`} src={article.image} alt="News article illustration"/>:<span className="story-image-fallback"/>}<div className="story-copy"><small>{article.source||"ONN"}　·　{article.topic}</small><h2>{article.headline}</h2></div><SignalMeta article={article}/><ArticleActions compact article={article} isSaved={saved.includes(article.id)} vote={votes[article.id]} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/></article>)}</section></div><SparkMagazine articles={shown.slice(1)} saved={saved} votes={votes} onVote={onVote} onSave={onSave} onDraft={onDraft} onShare={onShare} onHide={onHide} notify={notify}/></div>:<div className="empty"><h2>No signals in this topic</h2><p>Choose another topic to continue exploring.</p></div>}
  </div>
}

function Analytics({posts}){const counts={ideas:posts.filter(p=>p.stage==="Idea").length,drafts:posts.filter(p=>["Draft","Review"].includes(p.stage)).length,published:posts.filter(p=>p.stage==="Published").length,scheduled:posts.filter(p=>["Approved","Scheduled"].includes(p.stage)).length};const metrics=[["Posts published",counts.published,"Across connected platforms"],["Scheduled",counts.scheduled,"Ready to publish"],["Active drafts",counts.drafts,"Posts in progress"],["Ideas captured",counts.ideas,"Signals ready to develop"]];return <div className="insight-page workspace bauhaus-page"><header><div><h1>Analytics</h1><p>Measure what matters. Turn signals into strategic action.</p></div><div className="analytics-filters"><button>Last 30 days　⌄</button><button>All platforms　⌄</button></div></header><section className="metric-rail">{metrics.map(([label,value,detail],index)=><article key={label}><span className="card-post-mark" aria-hidden="true"/><Icon name={["Drafts","Calendar","Drafts","Ideas"][index]} size={24}/><small>{label}</small><b>{value}</b><span>{detail}</span></article>)}</section><section className="analytics-grid"><article className="trend-panel"><header><h2>Publishing activity</h2><span>Last 7 days</span></header><svg viewBox="0 0 720 250" role="img" aria-label="Publishing activity trend"><path className="grid-line" d="M35 40H700M35 100H700M35 160H700M35 220H700"/><path className="trend-area" d="M35 190 C95 175 120 130 180 150 S270 175 330 120 S430 155 485 90 S585 65 700 78 L700 220 L35 220Z"/><path className="trend-line" d="M35 190 C95 175 120 130 180 150 S270 175 330 120 S430 155 485 90 S585 65 700 78"/><g><circle cx="35" cy="190" r="5"/><circle cx="180" cy="150" r="5"/><circle cx="330" cy="120" r="5"/><circle cx="485" cy="90" r="5"/><circle cx="700" cy="78" r="5"/></g></svg><footer><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></footer></article><article className="pillar-performance"><h2>Content pillar performance</h2>{PILLARS.map((pillar,index)=><div key={pillar}><span>{pillar}</span><i><b style={{width:`${[86,68,53,34][index]}%`}}/></i><strong>{[43,28,18,11][index]}%</strong></div>)}</article><aside className="analytics-insight"><div className="card-post-mark insight-mark" aria-hidden="true"/><small>Key insight</small><h2>Trusted data posts drive the strongest saves.</h2><p>Posts grounded in evidence and clear outcomes consistently earn deeper engagement.</p></aside></section><section className="top-posts"><header><h2>Top-performing posts</h2><button>View all</button></header>{posts.slice(0,3).map((post,index)=><button key={post.id}><span className="post-rank">0{index+1}</span><span><b>{post.title}</b><small>{post.pillar}</small></span><strong>{["6.2%","4.8%","4.3%"][index]}</strong><small>Engagement</small></button>)}</section></div>}

const isoDate=(year,month,day)=>`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
function PostingCalendar({posts,open,create,movePost,onSelectDay,previewMode=false}){
  const deterministicPreview=previewMode||(typeof window!=="undefined"&&location.pathname.includes("canvaside-preview"));
  const [month,setMonth]=useState(()=>deterministicPreview?new Date(2026,7,1):new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [draggedId,setDraggedId]=useState(null),[dropDate,setDropDate]=useState(null);
  const year=month.getFullYear(),monthIndex=month.getMonth(),firstDay=new Date(year,monthIndex,1).getDay(),daysInMonth=new Date(year,monthIndex+1,0).getDate();
  const now=deterministicPreview?new Date("2026-08-01T12:00:00"):new Date(),todayDate=isoDate(now.getFullYear(),now.getMonth(),now.getDate());
  const ideaCount=deterministicPreview?3:posts.filter(post=>post.stage==="Idea").length,draftCount=deterministicPreview?5:posts.filter(post=>post.stage==="Draft").length,monthCount=deterministicPreview?6:posts.filter(post=>post.date.startsWith(`${year}-${String(monthIndex+1).padStart(2,"0")}`)).length;
  const cells=Array.from({length:42},(_,index)=>{const date=new Date(year,monthIndex,index-firstDay+1);return{day:date.getDate(),date:isoDate(date.getFullYear(),date.getMonth(),date.getDate()),outside:date.getMonth()!==monthIndex}});
  const byDate=useMemo(()=>{const map=new Map();posts.forEach(post=>{const group=map.get(post.date)||[];group.push(post);map.set(post.date,group)});return map},[posts]);
  return <>
    <div className="calendar-decoration" aria-hidden="true"><span/><i/><b/></div>
    <div className="calendar-filters"><div><button><b>in</b> LinkedIn　⌄</button><button>All statuses　⌄</button><button>All content pillars　⌄</button></div></div>
    <div className="calendar-toolbar"><div className="calendar-period" aria-label="Choose calendar month and year"><div className="period-stepper"><button aria-label="Previous month" onClick={()=>setMonth(new Date(year,monthIndex-1,1))}>‹</button><h2>{month.toLocaleDateString("en-US",{month:"long"})}</h2><button aria-label="Next month" onClick={()=>setMonth(new Date(year,monthIndex+1,1))}>›</button></div><div className="period-stepper"><button aria-label="Previous year" onClick={()=>setMonth(new Date(year-1,monthIndex,1))}>‹</button><h2>{year}</h2><button aria-label="Next year" onClick={()=>setMonth(new Date(year+1,monthIndex,1))}>›</button></div></div><div className="calendar-counts"><b>{ideaCount} Ideas</b><i/> <b>{draftCount} Drafts</b><i/> <span>{monthCount} posts this month</span></div></div>
    <section className="month-calendar" aria-label={`${month.toLocaleDateString("en-US",{month:"long",year:"numeric"})} posting calendar`}>
      <div className="weekday-row">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><b key={day}>{day}</b>)}</div>
      <div className="month-cells">{cells.map((cell,index)=>cell?<article className={`calendar-cell${dropDate===cell.date?" drop-target":""}`} key={cell.date} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move";setDropDate(cell.date)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget))setDropDate(null)}} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData("text/post-id")||draggedId;if(id)movePost(id,cell.date);setDraggedId(null);setDropDate(null)}}><button className={`day-header${cell.date===todayDate?" current-day":""}`} aria-current={cell.date===todayDate?"date":undefined} onClick={()=>onSelectDay?.(cell.date)}><b>{cell.day}</b><span>{(byDate.get(cell.date)||[]).length?`${(byDate.get(cell.date)||[]).length} post${(byDate.get(cell.date)||[]).length===1?"":"s"}`:"Plan day"}</span></button><div className="day-posts">{(byDate.get(cell.date)||[]).map(post=><button draggable="true" className={`calendar-post ${post.stage.toLowerCase()}${draggedId===post.id?" dragging":""}`} key={post.id} onDragStart={event=>{setDraggedId(post.id);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/post-id",String(post.id))}} onDragEnd={()=>{setDraggedId(null);setDropDate(null)}} onClick={()=>open(post.id)}><b>{post.title}</b><small>{post.stage} · {formatTime(post.time)}</small></button>)}<button className="ghost-post" onClick={()=>create("Idea",cell.date)} aria-label={`Create a new post on ${formatDate(cell.date)}`}><span>＋</span> New post</button></div></article>:<div className="calendar-cell outside" key={`blank-${index}`}/>)}</div>
    </section>
  </>
}
function Pillars(){return <section className="pillars"><h2>My content pillars</h2><div>{PILLARS.map((p,i)=><article key={p}><i>{["◉","↗","◇","○"][i]}</i><span><b>{p}</b><small>{["Practical AI adoption built on trusted data and governance.","Modernizing finance operations and reporting.","Data quality, governance, and integrity.","Turning insight into confident action."][i]}</small></span></article>)}</div></section>}

function Composer({post,patch,commitField,standalone=false,back,browse,canva,saveIdea,saveDraft,approve,remove,postNow,notify}){
  const [confirmDelete,setConfirmDelete]=useState(false),[showMedia,setShowMedia]=useState(Boolean(post.media?.url));
  const kind=post.stage==="Idea"?"idea":["Draft","Review"].includes(post.stage)?"draft":"post",platform=post.platform||"LinkedIn",formats=PLATFORM_FORMATS[platform],type=formats.includes(post.type)?post.type:formats[0],total=count(postText(post)),maxCharacters=PLATFORM_LIMITS[platform],canPublish=platform==="LinkedIn";
  const update=(key,value)=>{const next=count(postText({...post,[key]:value}));if(next<=maxCharacters||next<total)patch(key,value)};
  const choosePlatform=next=>{patch("platform",next);patch("type",PLATFORM_FORMATS[next][0])};
  const sourced=Boolean(post.sourceArticleId||post.sourceReference),commit=(key,value)=>commitField?.(key,value);
  return <div className="composer">{standalone?null:<div className="topbar"><button onClick={back}>← Back to content</button><div>{kind==="idea"?<><button onClick={saveIdea}>Save idea</button><button className="primary" onClick={saveDraft}>Develop into draft</button></>:kind==="draft"?<><button onClick={saveDraft}>Save draft</button><button className="primary" disabled={!canPublish} title={!canPublish?`Connect ${platform} to schedule publishing`:undefined} onClick={approve}>Approve &amp; schedule</button></>:<><button onClick={()=>navigator.clipboard.writeText(postText(post)).then(()=>notify("Post copied"))}>Copy post</button>{post.stage==="Scheduled"?<button onClick={saveDraft}>Cancel schedule</button>:null}<button className="danger" onClick={remove}>Delete post</button><button className="primary" disabled={!canPublish} title={!canPublish?`Connect ${platform} to publish`:undefined} onClick={postNow}>Post now</button></>}</div></div>}
  {standalone?<header className="composerhead editor-composerhead"><label><span className="editor-control-label">Platform</span><select aria-label="Platform" value={platform} onChange={e=>choosePlatform(e.target.value)}>{Object.keys(PLATFORM_FORMATS).map(name=><option key={name}>{name}</option>)}</select></label><label><span className="editor-control-label">Format</span><select aria-label="Format" value={type} onChange={e=>patch("type",e.target.value)}>{formats.map(format=><option key={format}>{format}</option>)}</select></label><label><span className="editor-control-label">Stage</span><select aria-label="Stage" value={post.stage} onChange={e=>patch("stage",e.target.value)}>{["Idea","Draft","Review","Approved","Scheduled","Published","Failed"].map(x=><option key={x}>{x}</option>)}</select></label><EditorDateTime label="Publishing date" type="date" icon="Calendar" value={post.date} onChange={value=>patch("date",value)}/><EditorDateTime label="Publishing time" type="time" icon="Clock" value={post.time||"09:00"} onChange={value=>patch("time",value)}/></header>:<><header className="composerhead"><h1>{`Edit ${kind}`}</h1><label>Stage<select value={post.stage} onChange={e=>patch("stage",e.target.value)}>{["Idea","Draft","Review","Approved","Scheduled","Published","Failed"].map(x=><option key={x}>{x}</option>)}</select></label><label>Publishing date<input type="date" value={post.date} onChange={e=>patch("date",e.target.value)}/></label><label>Publishing time<input type="time" value={post.time||"09:00"} onChange={e=>patch("time",e.target.value)}/></label><label>Timezone<input value={post.timezone||localTimezone()} readOnly/></label></header><section className="editor-controls"><div className="editor-control-row"><b>Platform</b><div className="platform-options">{Object.keys(PLATFORM_FORMATS).map(name=><button className={platform===name?"active":""} onClick={()=>choosePlatform(name)} key={name}><span className="platform-mark">{name==="LinkedIn"?"in":name==="Instagram"?"◎":name==="Facebook"?"f":"𝕏"}</span>{name}</button>)}</div></div><div className="editor-control-row"><b>Format</b><div className="typebar">{formats.map(x=><button className={type===x?"active":""} onClick={()=>patch("type",x)} key={x}>{x}</button>)}</div></div>{!canPublish?<small>{platform} is available for editing and preview. Connect it before publishing.</small>:null}</section></>}
  <section className="wysiwyg-editor-shell"><div className="wysiwyg-toolbar"><span className={total>maxCharacters?"over-limit":""}>{total.toLocaleString()} / {maxCharacters.toLocaleString()} characters</span><button type="button" className="add-image-link" onClick={()=>setShowMedia(value=>!value)}>{showMedia?"− Image":"＋ Image"}</button></div>{showMedia?<Media post={post} patch={patch} commit={value=>commit("media",value)} browse={browse} canva={canva}/>:null}<Preview post={post} type={type} platform={platform} editable sourced={sourced} update={update} commit={commit}/><TypeFields type={type} post={post} patch={patch}/>{post.publishingJob?<p className={`job-state ${post.publishingJob.status}`}><b>Publishing status: {post.publishingJob.status}</b>{post.publishingJob.lastError?<span>{post.publishingJob.lastError}</span>:null}</p>:null}<BrandCoach post={post} patch={patch} notify={notify} platform={platform}/></section>{standalone?<footer className="editor-final-actions"><button className="primary editor-schedule" disabled={!canPublish} title={!canPublish?`Connect ${platform} to schedule publishing`:undefined} onClick={approve}>Schedule</button><div><button type="button" className="editor-action-link" onClick={back}>Cancel</button><span aria-hidden="true">·</span>{confirmDelete?<span className="delete-confirm"><b>Delete this post?</b><button type="button" onClick={remove}>Yes, delete</button><button type="button" onClick={()=>setConfirmDelete(false)}>No, keep it</button></span>:<button type="button" className="editor-action-link danger-link" onClick={()=>setConfirmDelete(true)}>Delete</button>}</div></footer>:null}</div>
}
function ShareArticleDialog({article,close,confirm}){return <div className="modal share-article-modal" role="presentation" onClick={close}><section role="dialog" aria-modal="true" aria-labelledby="share-article-title" onClick={event=>event.stopPropagation()}><header><div><small>Share original article</small><h2 id="share-article-title">Confirm LinkedIn share</h2></div><button aria-label="Close share confirmation" onClick={close}>×</button></header><div className="share-article-preview">{article.image?<img src={article.image} alt=""/>:null}<div><small>{article.source}</small><strong>{article.headline}</strong><p>{article.summary}</p><span>{article.url}</span></div></div><p>PostingSignal will share the original article link as-is. No generated commentary will be added.</p><footer><button onClick={close}>Cancel</button><button className="primary" onClick={confirm}>Share to LinkedIn</button></footer></section></div>}
function EditorDateTime({label,type,icon,value,onChange}){return <label className="editor-date-time"><span>{label}</span><span className="editor-date-time-control"><input type={type} value={value} onChange={event=>onChange(event.target.value)}/><Icon name={icon} size={16}/></span></label>}
function BrandCoach({post,patch,notify,platform="LinkedIn"}){const suggestions=[{label:"Stronger hook",detail:"Lead with the measurable outcome to increase the stop rate.",apply:()=>patch("hook",post.hook||`The strongest leaders do not wait for perfect data. They make trust visible.`)},{label:"Body / clarity",detail:"Tighten the second paragraph for faster readability.",apply:()=>patch("body",post.body?.replace(/\n\n/g,"\n")||post.summary)},{label:"Closing question",detail:"Make the ask more specific and actionable.",apply:()=>patch("closing","What is one practical step your team could take this quarter?")},{label:"Tone",detail:"Keep the point confident, direct, and constructive."},{label:"Storytelling",detail:"Add one brief moment of context before the lesson."},{label:"Credibility",detail:"Support the argument with a measured outcome."},{label:"Authenticity",detail:"Include a personal observation only you could make."}];return <aside className="brand-coach"><header><div><h2>✦ AI Brand Coach</h2><p>Real-time guidance to strengthen your post.</p></div><span>Optional</span></header><section className="platform-recommendation"><b>Platform Recommendation</b><strong>{platform} <em>{platform==="LinkedIn"?"Recommended":"Preview mode"}</em></strong><p>This post is concise, insightful, and tailored to your {platform} audience.</p></section><section className="suggestions"><b>Personalization Suggestions</b>{suggestions.map(item=><article key={item.label}><div><strong>{item.label}</strong><p>{item.detail}</p></div><button onClick={()=>notify(`${item.label} suggestion reviewed`)}>Review</button>{item.apply?<button onClick={()=>{item.apply();notify(`${item.label} applied`)}}>Apply</button>:null}</article>)}</section><small>AI suggestions are optional. You’re in control.</small></aside>}
function Field({label,value="",rows=3,onChange}){return <label className="field"><span>{label}</span>{rows===1?<input value={value} onChange={e=>onChange(e.target.value)}/>:<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function InlineField({label,placeholder,hideLabel=false,value="",onChange,onCommit}){
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState(value),cancelled=useRef(false);
  useEffect(()=>{if(!editing)setDraft(value)},[value,editing]);
  const finish=()=>{setEditing(false);if(cancelled.current){cancelled.current=false;setDraft(value);return}if(draft!==value){onChange(draft);onCommit?.(draft)}};
  const keyDown=event=>{if(event.key==="Escape"){event.preventDefault();cancelled.current=true;event.currentTarget.blur()}};
  return <section className={`inline-edit-field${editing?" is-editing":""}${hideLabel?" no-label":""}`}><span className="inline-edit-label">{label}</span>{editing?<textarea autoFocus aria-label={label} rows={Math.max(1,draft.split("\n").length)} value={draft} placeholder={placeholder} onChange={event=>setDraft(event.target.value)} onKeyDown={keyDown} onBlur={finish}/>:<button type="button" className={!value?"is-placeholder":""} onClick={()=>setEditing(true)}>{value||placeholder}</button>}</section>
}
function TypeFields({type,post,patch}){if(type==="Poll"){const n=Number(post.pollOptionCount||2);return <section className="context"><Field label={`Poll question · ${count(post.pollQuestion)} / 140`} value={post.pollQuestion||""} onChange={v=>patch("pollQuestion",v.slice(0,140))}/>{Array.from({length:n},(_,i)=><Field key={i} label={`Poll option ${i+1} · ${count(post[`poll${i}`])} / 30`} value={post[`poll${i}`]||""} onChange={v=>patch(`poll${i}`,v.slice(0,30))}/>)}{n<4?<button onClick={()=>patch("pollOptionCount",n+1)}>＋ Add option</button>:null}</section>};if(type==="Document")return <Document post={post} patch={patch}/>;return null}
function Document({post,patch}){const upload=async e=>{const file=e.target.files?.[0];if(!file||post.document)return;const body=new FormData();body.append("document",file);const r=await fetch(`${API}/api/documents`,{method:"POST",body});const data=await r.json();if(r.ok)patch("document",data)};return <section className="context"><b>Document attachment</b><small>One document · PDF, PPT, PPTX, DOC, or DOCX · 100 MB maximum</small>{post.document?<div className="document"><span>{post.document.name}</span><button onClick={()=>{fetch(`${API}/api/documents/${post.document.id}`,{method:"DELETE"});patch("document",null)}}>Remove</button></div>:<label className="upload">Attach document<input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx" onChange={upload}/></label>}</section>}
function Media({post,patch,commit,browse,canva}){const [uploading,setUploading]=useState(false);const upload=event=>{const file=event.target.files?.[0];if(!file)return;setUploading(true);const reader=new FileReader();reader.onload=()=>{const media={url:String(reader.result),alt:file.name,source:"Uploaded"};patch("media",media);commit?.(media);setUploading(false)};reader.onerror=()=>setUploading(false);reader.readAsDataURL(file)};return <section className={`media editor-media${uploading?" is-uploading":""}`}><div><b>Post image</b><small>{uploading?"Uploading image…":post.media?.source||"Add an image to this post"}</small></div>{post.media?.url?<img src={post.media.url} alt={post.media.alt||"Post"}/>:<div className="imageplaceholder">{uploading?"Uploading…":"Image preview"}</div>}<div><label className="media-upload">Upload image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={upload}/></label><button onClick={browse}>Browse Unsplash</button><button onClick={canva}>Create in Canva ↗</button></div></section>}
function Preview({post,type,platform="LinkedIn",editable=false,sourced=false,update,commit}){
  const {user}=useUser(),[linkedInName,setLinkedInName]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch("/api/linkedin/status",{signal:controller.signal}).then(response=>response.ok?response.json():null).then(data=>{if(data?.connected&&data.connection?.displayName)setLinkedInName(data.connection.displayName)}).catch(()=>{});return()=>controller.abort()},[]);
  const name=linkedInName||user?.fullName||user?.firstName||user?.primaryEmailAddress?.emailAddress||"PostingSignal member",initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"PS",headline=typeof user?.publicMetadata?.headline==="string"?user.publicMetadata.headline:"PostingSignal member",hasAvatar=Boolean(user?.imageUrl),avatarStyle=hasAvatar?{backgroundImage:`url("${user.imageUrl}")`}:undefined,copy=[post.title,post.hook,post.body,post.closing].filter(Boolean),handle=`@${name.toLowerCase().replace(/[^a-z0-9]+/g,"").slice(0,18)||"postingsignal"}`,media=post.media?.url?<img src={post.media.url} alt={post.media.alt||"Post"}/>:<div className="platform-media-placeholder"><span>＋</span><b>{type} media preview</b></div>,avatar=<b className={`preview-avatar${hasAvatar?" has-image":""}`} style={avatarStyle} aria-label={`${name} profile photo`}>{initials}</b>;
  const body=editable?<div className={`copy editable-preview-copy${sourced?" sourced-copy":" new-copy"}`}><InlineField label="Title" placeholder="Give this post a clear title" hideLabel={sourced} value={post.title} onChange={value=>update("title",value)} onCommit={value=>commit("title",value)}/><InlineField label="Hook" placeholder="Open with a thought that makes the reader stop" hideLabel={sourced} value={post.hook} onChange={value=>update("hook",value)} onCommit={value=>commit("hook",value)}/><InlineField label="Body" placeholder="Develop your perspective, insight, or story" hideLabel={sourced} value={post.body} onChange={value=>update("body",value)} onCommit={value=>commit("body",value)}/><InlineField label="Closing question" placeholder="Invite the reader into the conversation" hideLabel={sourced} value={post.closing} onChange={value=>update("closing",value)} onCommit={value=>commit("closing",value)}/></div>:<div className="copy">{copy.map((value,index)=><p className={index===0?"title":""} key={index}>{value}</p>)}</div>;
  let card;
  if(platform==="Instagram")card=<article className="instagram-card"><header>{avatar}<span><strong>{handle.slice(1)}</strong><small>Sponsored · {type}</small></span><i>•••</i></header>{media}<footer>♡　◯　➤ <span>▱</span></footer><div className="instagram-caption"><b>{handle.slice(1)}</b>{body}<small>View all comments</small></div></article>;
  else if(platform==="Facebook")card=<article className="facebook-card"><header>{avatar}<span><strong>{name}</strong><small>Just now · 🌐</small></span><i>•••</i></header>{body}{type!=="Feed post"||post.media?.url?media:null}<div className="engagement">♡ Be the first to react</div><footer>Like　 Comment　 Share</footer></article>;
  else if(platform==="X")card=<article className="x-card"><header>{avatar}<span><strong>{name}</strong><small>{handle} · now</small></span><i>•••</i></header><div className="x-body">{body}{type==="Thread"?<small>1 / 2 · Continue your thread</small>:null}{post.media?.url?media:null}</div><footer>◯　↻　♡　⌁　↗</footer></article>;
  else card=<article className="linkedin-card"><header>{avatar}<span><strong>{name}</strong><small>{headline}</small><small>Now · 🌐</small></span><i>•••</i></header>{body}{type==="Poll"?<div className="poll"><b>{post.pollQuestion||"What is your perspective?"}</b>{Array.from({length:Number(post.pollOptionCount||2)},(_,i)=><button key={i}>{post[`poll${i}`]||`Option ${i+1}`}</button>)}</div>:type==="Document"&&post.document?<div className="docpreview">▤ {post.document.name}</div>:post.media?.url?media:null}<footer>♡ Like　◯ Comment　↻ Repost　➤ Send</footer></article>;
  return <section className={`preview platform-preview platform-${platform.toLowerCase()}${editable?" is-editable-preview":""}`}>{editable?null:<div className="preview-heading"><h2>{platform} preview</h2><span>{type}</span></div>}{card}</section>
}

function MediaPicker({post,choose,close,canva}){const [query,setQuery]=useState(post.pillar),[results,setResults]=useState([]),[error,setError]=useState("");const search=async e=>{e.preventDefault();const key=localStorage.getItem("signal-unsplash-key");if(!key)return setError("Add your Unsplash Access Key below.");const r=await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=12`,{headers:{Authorization:`Client-ID ${key}`}});const data=await r.json();if(!r.ok)return setError(data.errors?.[0]||"Search failed");setResults(data.results.map(x=>({id:x.id,url:x.urls.regular,thumb:x.urls.small,alt:x.alt_description||query,credit:x.user.name,source:"Unsplash",downloadLocation:x.links.download_location})));setError("")};return <div className="modal"><section><header><div><h2>Choose a post image</h2><p>Search Unsplash or continue in Canva.</p></div><button onClick={close}>✕</button></header><form onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Unsplash"/><button className="primary">Search</button></form><label className="key">Unsplash Access Key<input type="password" defaultValue={localStorage.getItem("signal-unsplash-key")||""} onChange={e=>localStorage.setItem("signal-unsplash-key",e.target.value)}/></label>{error?<p className="error">{error}</p>:null}<div className="mediaresults">{results.map(x=><button key={x.id} onClick={()=>choose(x)}><img src={x.thumb}/><span>Photo by {x.credit}</span></button>)}</div><button className="canva" onClick={canva}>Create in Canva ↗</button></section></div>}
function BrandSettings(){const [brand,setBrand]=useState(BRAND_DEFAULTS),[status,setStatus]=useState("");useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("posting-signal-brand"));if(saved){const {brandName:legacyBrandName,...current}=saved;setBrand({...BRAND_DEFAULTS,...current})}}catch{}},[]);const update=(key,value)=>{setBrand(current=>({...current,[key]:value}));setStatus("Unsaved changes")};const save=event=>{event.preventDefault();localStorage.setItem("posting-signal-brand",JSON.stringify(brand));setStatus("Changes saved")};const reset=()=>{setBrand(BRAND_DEFAULTS);localStorage.removeItem("posting-signal-brand");setStatus("Restored from Social Encounter")};const attributes=[{key:"brandPromise",label:"Brand promise"},{key:"voice",label:"Voice"},{key:"audience",label:"Primary audience"},{key:"pillars",label:"Content pillars"},{key:"personality",label:"Personality"},{key:"useOften",label:"Use often"},{key:"avoid",label:"Avoid"}],colors=[{key:"signalTeal",label:"Signal teal"},{key:"actionRed",label:"Action red"},{key:"editorialInk",label:"Editorial ink"}];return <form className="brand-settings" onSubmit={save}><header><div><h1>Brand</h1><p>Mock brand attributes supplied by the Social Encounter state integration.</p></div><span className="brand-sync-state"><i/> Social Encounter · Synced</span></header><section className="brand-identity"><div className="brand-monogram">BF</div><div className="brand-identity-fields"><label>Brand Focus<textarea rows="2" placeholder="For example: start a new business or become an AI subject-matter expert" value={brand.brandFocus} onChange={event=>update("brandFocus",event.target.value)}/></label><label>Positioning statement<textarea rows="2" value={brand.tagline} onChange={event=>update("tagline",event.target.value)}/></label></div></section><div className="brand-attributes">{attributes.map(attribute=><label key={attribute.key}><span>{attribute.label}</span><textarea rows="2" value={brand[attribute.key]} onChange={event=>update(attribute.key,event.target.value)}/></label>)}</div><section className="brand-colors"><b>Brand colors</b><div>{colors.map(color=><label key={color.key}><input type="color" value={/^#[0-9A-F]{6}$/i.test(brand[color.key])?brand[color.key]:BRAND_DEFAULTS[color.key]} onChange={event=>update(color.key,event.target.value.toUpperCase())}/><span>{color.label}</span><input className="brand-hex" value={brand[color.key]} maxLength="7" onChange={event=>update(color.key,event.target.value.toUpperCase())}/></label>)}</div></section><footer className="brand-actions"><span>{status||"All changes are stored in this browser."}</span><button type="button" onClick={reset}>Reset synced values</button><button className="primary" type="submit">Save changes</button></footer><small className="brand-mock-note">Mock integration state for design and workflow validation.</small></form>}
function LinkedInConnection({notify}){const [status,setStatus]=useState({loading:true,connected:false,connection:null});useEffect(()=>{const controller=new AbortController();const load=async()=>{try{const response=await fetch("/api/linkedin/status",{signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||"Connection status unavailable");setStatus({...data,loading:false})}catch{if(!controller.signal.aborted)setStatus({loading:false,connected:false,connection:null})}};load();return()=>controller.abort()},[]);const disconnect=async()=>{if(!confirm("Disconnect this LinkedIn account?"))return;const response=await fetch("/api/linkedin/status",{method:"DELETE"});if(response.ok){setStatus({loading:false,connected:false,connection:null});notify("LinkedIn disconnected")}else notify("LinkedIn could not be disconnected")};const expiry=status.connection?.expiresAt?`Access expires ${new Date(status.connection.expiresAt).toLocaleDateString()}`:"LinkedIn access is active";return <section className="connection-card"><div className="connection-heading"><div className="connection-copy"><h2>LinkedIn publishing</h2><p>{status.loading?"Checking connection…":status.connected?`Connected as ${status.connection?.displayName||"LinkedIn member"}`:"Connect your LinkedIn account to publish approved posts directly."}</p>{status.connected?<small className="connection-expiry">{expiry}</small>:null}</div>{status.connected?<button type="button" className="connection-state connected disconnect-trigger" onClick={disconnect} aria-label="Disconnect LinkedIn"><span className="connected-label">Connected</span><span className="disconnect-label">Disconnect</span></button>:<span className="connection-state disconnected">{status.loading?"Checking":"Not connected"}</span>}</div>{status.connected?null:<a className="primary connection-button" href="/api/linkedin/connect">Connect LinkedIn</a>}</section>}
function IntegrationPlaceholder({name,description}){return <section className="integration-placeholder"><div><h2>{name}</h2><p>{description}</p></div><span>Coming Soon</span></section>}
function Settings({notify}){return <div className="settings"><h1>Integrations</h1><p>Connect the services PostingSignal uses to prepare and publish your content.</p><div className="integration-list"><LinkedInConnection notify={notify}/><IntegrationPlaceholder name="Canva" description="Create and attach branded visuals to your posts."/><IntegrationPlaceholder name="Unsplash" description="Find professional images for your content."/><IntegrationPlaceholder name="Social Encounter" description="Coordinate content and engagement across your social presence."/><IntegrationPlaceholder name="Career Pivot" description="Turn career strategy and progress into shareable content."/></div></div>}
