"use client";

import React, { useEffect, useMemo, useState } from "react";

const API = "";
const PILLARS = ["AI readiness", "Finance transformation", "Trusted data", "Executive decision-making"];
const NAV = ["Today", "Calendar", "Ideas", "Drafts", "Library", "Settings"];
const TYPES = ["Standard post", "Event", "Celebrate", "Hiring", "Poll", "Document", "Find an expert"];
const seed = [
  {id:1,date:"2026-07-20",title:"Why AI readiness starts with trusted data",summary:"AI pilots fail when data cannot be trusted. Here is the foundation I help organizations build.",pillar:"AI readiness",stage:"Review",hook:"AI readiness does not begin with a model. It begins with data leaders can trust.",body:"The organizations moving fastest with AI are not skipping governance. They are investing in it.\n\nA trusted data foundation means shared definitions, clear ownership, reliable pipelines, and controls that make quality visible.",closing:"Where is the biggest trust gap in your organization’s data today?"},
  {id:2,date:"2026-07-22",title:"From five days to three hours: redesigning executive reporting",summary:"How we cut monthly reporting from five days to under three hours—and what it unlocked.",pillar:"Finance transformation",stage:"Draft",hook:"We cut monthly executive reporting from five days to under three hours. Here is what changed.",body:"The breakthrough was not a new tool—it was a new design.\n\nWe standardized data definitions, automated collection and validation, and rebuilt the report layer around clarity and decision value.",closing:"What is one report your team could redesign this quarter?"},
  {id:3,date:"2026-07-24",title:"The hidden cost of KPI disagreement",summary:"When KPIs do not agree, decisions slow down.",pillar:"Trusted data",stage:"Idea",hook:"",body:"",closing:""},
  {id:4,date:"2026-07-27",title:"What Finance should ask before automating a process",summary:"Automation without the right questions just automates waste.",pillar:"Finance transformation",stage:"Idea",hook:"",body:"",closing:""},
  {id:5,date:"2026-07-29",title:"Data integrity is not a tech problem—it is a leadership decision",summary:"How strong data governance drives better insight and builds executive trust.",pillar:"Trusted data",stage:"Review",hook:"",body:"",closing:""},
  {id:6,date:"2026-07-31",title:"From insight to action: the executive reporting chain",summary:"A simple model to connect data, insight, decision and outcome.",pillar:"Executive decision-making",stage:"Draft",hook:"",body:"",closing:""},
  {id:7,date:"2026-08-03",title:"Three questions every CFO should ask about AI",summary:"A short checklist to separate signal from noise in AI initiatives.",pillar:"AI readiness",stage:"Approved",hook:"Before approving another AI pilot, ask three questions.",body:"Is the underlying data trusted? Is the business decision clear? Is there an accountable owner for the outcome?",closing:"Which question is most often missing from the conversation?"}
];
const count = (value="") => [...value].length;
const postText = p => [p.title,p.hook,p.body,p.closing].filter(Boolean).join("\n\n");
const formatDate = d => new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));

export default function PostingSignalApp(){
  const [posts,setPosts]=useState(seed),[hydrated,setHydrated]=useState(false);
  const [active,setActive]=useState("Today"),[selected,setSelected]=useState(2),[editing,setEditing]=useState(false),[toast,setToast]=useState(""),[mediaOpen,setMediaOpen]=useState(false);
  useEffect(()=>{try{setPosts(JSON.parse(localStorage.getItem("signal-posts"))||seed)}catch{setPosts(seed)}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("signal-posts",JSON.stringify(posts))},[posts,hydrated]);
  const post=posts.find(p=>p.id===selected)||posts[0];
  const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)};
  const patch=(key,value)=>setPosts(all=>all.map(p=>p.id===selected?{...p,[key]:value}:p));
  const movePost=(id,date)=>{setPosts(all=>all.map(p=>p.id===id?{...p,date,updatedAt:new Date().toISOString()}:p));notify(`Post moved to ${formatDate(date)}`)};
  const openPost=id=>{setSelected(id);setEditing(true)};
  const create=(stage="Idea",date=new Date().toISOString().slice(0,10))=>{const id=Math.max(0,...posts.map(p=>p.id))+1;const next={id,date,title:stage==="Idea"?"Untitled idea":"Untitled post",summary:"Add a short premise.",pillar:PILLARS[0],stage,hook:"",body:"",closing:""};setPosts(v=>[next,...v]);setSelected(id);setEditing(true)};
  const saveStage=(stage,message)=>{setPosts(all=>{const next=all.map(p=>p.id===selected?{...p,stage,updatedAt:new Date().toISOString()}:p);localStorage.setItem("signal-posts",JSON.stringify(next));return next});notify(message)};
  const remove=()=>{if(!confirm(`Delete “${post.title}”? This cannot be undone.`))return;setPosts(v=>v.filter(p=>p.id!==selected));setEditing(false);notify("Post deleted")};
  const postNow=async()=>{const popup=window.open("https://www.linkedin.com/feed/?shareActive=true","_blank");await navigator.clipboard.writeText(postText(post));notify(popup?"Copied. Paste into LinkedIn to review and publish.":"Copied. Allow pop-ups to open LinkedIn.")};
  const openCanva=async()=>{const popup=window.open("about:blank","posting-signal-canva");try{const response=await fetch(`${API}/api/canva/launch`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({postId:post.id,title:post.title,imageUrl:post.media?.url})});const data=await response.json();if(!response.ok)throw Error(data.error||"Canva could not start");popup.location=data.launchUrl}catch(error){popup?.close();notify(error.message)}};
  useEffect(()=>{const q=new URLSearchParams(location.search),designId=q.get("canvaDesignId"),postId=q.get("canvaPostId");if(!designId||!postId)return;fetch(`${API}/api/canva/export`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({designId,postId})}).then(r=>r.json()).then(data=>setPosts(all=>all.map(p=>String(p.id)===postId?{...p,media:{url:data.url,alt:`Canva design for ${p.title}`,source:"Canva",designId}}:p))).finally(()=>history.replaceState({},"",location.pathname))},[]);
  const composer=editing?<Composer post={post} patch={patch} back={()=>setEditing(false)} browse={()=>setMediaOpen(true)} canva={openCanva} saveIdea={()=>saveStage("Idea","Idea saved locally")} saveDraft={()=>saveStage("Draft","Draft saved locally")} approve={()=>saveStage("Approved",`Approved and scheduled for ${formatDate(post.date)}`)} remove={remove} postNow={postNow} notify={notify}/>:null;
  return <div className="shell">
    <Sidebar active={active} onNav={n=>{setActive(n);setEditing(false)}}/>
    <main className={editing&&active!=="Calendar"?"editing":""}>
      {editing&&active!=="Calendar"?composer:active==="Settings"?<Settings notify={notify}/>:<Workspace active={active} posts={posts} open={openPost} create={create} movePost={movePost} calendarEditor={editing?composer:null} closeCalendarEditor={()=>setEditing(false)}/>} 
      {toast?<div className="toast">{toast}</div>:null}
    </main>
    {mediaOpen?<MediaPicker post={post} choose={m=>{patch("media",m);setMediaOpen(false);notify("Image added")}} close={()=>setMediaOpen(false)} canva={openCanva}/>:null}
  </div>
}

function Sidebar({active,onNav}){return <aside className="sidebar"><div className="brand">PostingSignal<span>LinkedIn content workspace</span></div><nav>{NAV.map(n=><button key={n} className={`${active===n?"active ":""}${n==="Settings"?"nav-settings":""}`} onClick={()=>onNav(n)}><i>{({Today:"⌂",Calendar:"□",Ideas:"◯",Drafts:"✎",Library:"▤",Settings:"⚙"})[n]}</i>{n}</button>)}</nav><div className="identity"><b>EP</b><span>Earl Powery<small>Enterprise leader</small></span><button className={active==="Settings"?"active":""} aria-label="Settings" title="Settings" onClick={()=>onNav("Settings")}>⚙</button></div></aside>}

function Workspace({active,posts,open,create,movePost,calendarEditor,closeCalendarEditor}){
  const copy={Today:["Content workspace","Plan, craft, and prepare authoritative LinkedIn content."],Calendar:["Calendar","Plan and manage every post"],Ideas:["Idea backlog","Develop promising topics into complete LinkedIn posts."],Drafts:["Drafts in progress","Continue writing, review, and approve active work."],Library:["Content library","Reuse approved posts, images, and documents."]}[active];
  const shown=active==="Ideas"?posts.filter(p=>p.stage==="Idea"):active==="Drafts"?posts.filter(p=>["Draft","Review"].includes(p.stage)):active==="Library"?posts.filter(p=>p.stage==="Approved"):posts;
  return <div className={`workspace${active==="Calendar"?" calendar-workspace":""}`}><header><div><h1>{copy[0]}</h1><p>{copy[1]}</p></div>{active!=="Calendar"?<button className="primary" onClick={()=>create(active==="Ideas"?"Idea":active==="Drafts"?"Draft":"Idea")}>＋ {active==="Ideas"?"New Idea":active==="Drafts"?"New draft":"New post"}</button>:null}</header>
  {active==="Today"?<Pillars/>:null}
  {active==="Calendar"?<PostingCalendar posts={posts} open={open} create={create} movePost={movePost} calendarEditor={calendarEditor} closeCalendarEditor={closeCalendarEditor}/>:<section className={active==="Today"?"timeline":"cards"}>{shown.map(p=><button key={p.id} className="item" onClick={()=>open(p.id)}><time>{formatDate(p.date)}<small>9:00 AM</small></time><span className="itemcopy"><b>{p.title}</b><small>{p.summary}</small></span><span className="pillar">{p.pillar}</span><span className={`stage ${p.stage.toLowerCase()}`}>{p.stage}</span></button>)}</section>}
  {!shown.length?<div className="empty"><h2>No {active.toLowerCase()} yet</h2><p>Create one to get started.</p></div>:null}</div>
}

const isoDate=(year,month,day)=>`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
function PostingCalendar({posts,open,create,movePost,calendarEditor,closeCalendarEditor}){
  const [month,setMonth]=useState(()=>{const now=new Date();return new Date(now.getFullYear(),now.getMonth(),1)});
  const [openDay,setOpenDay]=useState(null);
  const [draggedId,setDraggedId]=useState(null),[dropDate,setDropDate]=useState(null);
  const year=month.getFullYear(),monthIndex=month.getMonth(),firstDay=new Date(year,monthIndex,1).getDay(),daysInMonth=new Date(year,monthIndex+1,0).getDate();
  const now=new Date(),todayDate=isoDate(now.getFullYear(),now.getMonth(),now.getDate());
  const ideaCount=posts.filter(post=>post.stage==="Idea").length,draftCount=posts.filter(post=>post.stage==="Draft").length,monthCount=posts.filter(post=>post.date.startsWith(`${year}-${String(monthIndex+1).padStart(2,"0")}`)).length;
  const cells=Array.from({length:42},(_,index)=>{const day=index-firstDay+1;return day>=1&&day<=daysInMonth?{day,date:isoDate(year,monthIndex,day)}:null});
  const byDate=useMemo(()=>{const map=new Map();posts.forEach(post=>{const group=map.get(post.date)||[];group.push(post);map.set(post.date,group)});return map},[posts]);
  const dayPosts=openDay?byDate.get(openDay)||[]:[];
  return <>
    <div className="calendar-toolbar"><div className="calendar-period" aria-label="Choose calendar month and year"><div className="period-stepper"><button aria-label="Previous month" onClick={()=>setMonth(new Date(year,monthIndex-1,1))}>‹</button><h2>{month.toLocaleDateString("en-US",{month:"long"})}</h2><button aria-label="Next month" onClick={()=>setMonth(new Date(year,monthIndex+1,1))}>›</button></div><div className="period-stepper"><button aria-label="Previous year" onClick={()=>setMonth(new Date(year-1,monthIndex,1))}>‹</button><h2>{year}</h2><button aria-label="Next year" onClick={()=>setMonth(new Date(year+1,monthIndex,1))}>›</button></div></div><div className="calendar-counts"><b>{ideaCount} Ideas</b><i/> <b>{draftCount} Drafts</b><i/> <span>{monthCount} posts this month</span></div></div>
    <section className="month-calendar" aria-label={`${month.toLocaleDateString("en-US",{month:"long",year:"numeric"})} posting calendar`}>
      <div className="weekday-row">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><b key={day}>{day}</b>)}</div>
      <div className="month-cells">{cells.map((cell,index)=>cell?<article className={`calendar-cell${dropDate===cell.date?" drop-target":""}`} key={cell.date} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move";setDropDate(cell.date)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget))setDropDate(null)}} onDrop={event=>{event.preventDefault();const id=Number(event.dataTransfer.getData("text/post-id")||draggedId);if(id)movePost(id,cell.date);setDraggedId(null);setDropDate(null)}}><button className={`day-header${cell.date===todayDate?" current-day":""}`} aria-current={cell.date===todayDate?"date":undefined} onClick={()=>setOpenDay(cell.date)}><b>{cell.day}</b><span>{(byDate.get(cell.date)||[]).length?`${(byDate.get(cell.date)||[]).length} post${(byDate.get(cell.date)||[]).length===1?"":"s"}`:"Plan day"}</span></button><div className="day-posts">{(byDate.get(cell.date)||[]).map(post=><button draggable="true" className={`calendar-post ${post.stage.toLowerCase()}${draggedId===post.id?" dragging":""}`} key={post.id} onDragStart={event=>{setDraggedId(post.id);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/post-id",String(post.id))}} onDragEnd={()=>{setDraggedId(null);setDropDate(null)}} onClick={()=>open(post.id)}><b>{post.title}</b><small>{post.stage} · 9:00 AM</small></button>)}<button className="ghost-post" onClick={()=>create("Idea",cell.date)} aria-label={`Create a new post on ${formatDate(cell.date)}`}><span>＋</span> New post</button></div></article>:<div className="calendar-cell outside" key={`blank-${index}`}/>)}</div>
      {calendarEditor?<div className="calendar-editor-overlay" role="presentation" onClick={closeCalendarEditor}><section className="calendar-editor-window" role="dialog" aria-modal="true" aria-label="Edit calendar post" onClick={event=>event.stopPropagation()}>{calendarEditor}</section></div>:null}
    </section>
    {openDay?<div className="day-overlay" onClick={()=>setOpenDay(null)}><aside className="day-pane" onClick={event=>event.stopPropagation()}><header><div><small>Posting day</small><h2>{new Date(`${openDay}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</h2><p>{dayPosts.length?`${dayPosts.length} scheduled post${dayPosts.length===1?"":"s"}`:"No posts scheduled yet"}</p></div><button aria-label="Close day pane" onClick={()=>setOpenDay(null)}>✕</button></header><button className="primary day-new" onClick={()=>{setOpenDay(null);create("Idea",openDay)}}>＋ New post for this day</button><div className="day-pane-posts">{dayPosts.map(post=><button key={post.id} onClick={()=>{setOpenDay(null);open(post.id)}}><span><b>{post.title}</b><small>{post.pillar} · {post.stage}</small></span><i>9:00 AM　›</i></button>)}{!dayPosts.length?<div className="day-empty"><b>This day is open</b><p>Create a post now or close this pane and choose another date.</p></div>:null}</div></aside></div>:null}
  </>
}
function Pillars(){return <section className="pillars"><h2>My content pillars</h2><div>{PILLARS.map((p,i)=><article key={p}><i>{["◉","↗","◇","○"][i]}</i><span><b>{p}</b><small>{["Practical AI adoption built on trusted data and governance.","Modernizing finance operations and reporting.","Data quality, governance, and integrity.","Turning insight into confident action."][i]}</small></span></article>)}</div></section>}

function Composer({post,patch,back,browse,canva,saveIdea,saveDraft,approve,remove,postNow,notify}){
  const kind=post.stage==="Idea"?"idea":["Draft","Review"].includes(post.stage)?"draft":"post",total=count(postText(post)),type=post.type||"Standard post";
  const update=(key,value)=>{if(count(postText({...post,[key]:value}))<=3000)patch(key,value)};
  return <div className="composer"><div className="topbar"><button onClick={back}>← Back to content</button><div>{kind==="idea"?<><button onClick={saveIdea}>Save idea</button><button className="primary" onClick={saveDraft}>Develop into draft</button></>:kind==="draft"?<><button onClick={saveDraft}>Save draft</button><button className="primary" onClick={approve}>Approve &amp; schedule</button></>:<><button onClick={()=>navigator.clipboard.writeText(postText(post)).then(()=>notify("Post copied"))}>Copy post</button><button className="danger" onClick={remove}>Delete post</button><button className="primary" onClick={postNow}>Post now</button></>}</div></div>
  <header className="composerhead"><h1>Edit {kind}</h1><label>Stage<select value={post.stage} onChange={e=>patch("stage",e.target.value)}>{["Idea","Draft","Review","Approved"].map(x=><option key={x}>{x}</option>)}</select></label><label>Scheduled for<input type="date" value={post.date} onChange={e=>patch("date",e.target.value)}/></label></header>
  <div className="typebar">{TYPES.map(x=><button className={type===x?"active":""} onClick={()=>patch("type",x)} key={x}>{x}</button>)}</div>
  <div className="columns"><section className="fields"><div className="limit"><b>LinkedIn post text</b><span>{total.toLocaleString()} / 3,000 characters</span></div><Field label="Title" value={post.title} onChange={v=>update("title",v)}/><Field label="Hook" value={post.hook} onChange={v=>update("hook",v)}/><Field label="Body" rows={8} value={post.body} onChange={v=>update("body",v)}/><Field label="Closing question" rows={2} value={post.closing} onChange={v=>update("closing",v)}/><TypeFields type={type} post={post} patch={patch}/><Media post={post} browse={browse} canva={canva}/><div className="meta"><label>Content pillar<select value={post.pillar} onChange={e=>patch("pillar",e.target.value)}>{PILLARS.map(x=><option key={x}>{x}</option>)}</select></label><label>Audience<select value={post.audience||"Finance leaders, CFOs, FP&A professionals"} onChange={e=>patch("audience",e.target.value)}><option>Finance leaders, CFOs, FP&A professionals</option><option>Data & technology leaders</option><option>Transformation executives</option></select></label></div><p className="safety">Human approval is required before a post is ready for LinkedIn. Nothing is posted automatically.</p></section><Preview post={post} type={type}/></div></div>
}
function Field({label,value="",rows=3,onChange}){return <label className="field"><span>{label}</span>{rows===1?<input value={value} onChange={e=>onChange(e.target.value)}/>:<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function TypeFields({type,post,patch}){if(type==="Poll"){const n=Number(post.pollOptionCount||2);return <section className="context"><Field label={`Poll question · ${count(post.pollQuestion)} / 140`} value={post.pollQuestion||""} onChange={v=>patch("pollQuestion",v.slice(0,140))}/>{Array.from({length:n},(_,i)=><Field key={i} label={`Poll option ${i+1} · ${count(post[`poll${i}`])} / 30`} value={post[`poll${i}`]||""} onChange={v=>patch(`poll${i}`,v.slice(0,30))}/>)}{n<4?<button onClick={()=>patch("pollOptionCount",n+1)}>＋ Add option</button>:null}</section>};if(type==="Document")return <Document post={post} patch={patch}/>;return null}
function Document({post,patch}){const upload=async e=>{const file=e.target.files?.[0];if(!file||post.document)return;const body=new FormData();body.append("document",file);const r=await fetch(`${API}/api/documents`,{method:"POST",body});const data=await r.json();if(r.ok)patch("document",data)};return <section className="context"><b>Document attachment</b><small>One document · PDF, PPT, PPTX, DOC, or DOCX · 100 MB maximum</small>{post.document?<div className="document"><span>{post.document.name}</span><button onClick={()=>{fetch(`${API}/api/documents/${post.document.id}`,{method:"DELETE"});patch("document",null)}}>Remove</button></div>:<label className="upload">Attach document<input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx" onChange={upload}/></label>}</section>}
function Media({post,browse,canva}){return <section className="media"><div><b>Post image</b><small>{post.media?.source||"Auto-selected recommendation"}</small></div>{post.media?.url?<img src={post.media.url} alt={post.media.alt||"Post"}/>:<div className="imageplaceholder">Image preview</div>}<div><button onClick={browse}>Browse Unsplash</button><button onClick={canva}>Create in Canva ↗</button></div></section>}
function Preview({post,type}){return <section className="preview"><h2>LinkedIn preview</h2><article><header><b>EP</b><span><strong>Earl Powery</strong><small>Enterprise transformation leader</small><small>Now · 🌐</small></span><i>•••</i></header><div className="copy">{[post.title,post.hook,post.body,post.closing].filter(Boolean).map((x,i)=><p className={i===0?"title":""} key={i}>{x}</p>)}</div>{type==="Poll"?<div className="poll"><b>{post.pollQuestion||"What is your perspective?"}</b>{Array.from({length:Number(post.pollOptionCount||2)},(_,i)=><button key={i}>{post[`poll${i}`]||`Option ${i+1}`}</button>)}</div>:post.document?<div className="docpreview">▤ {post.document.name}</div>:post.media?.url?<img src={post.media.url} alt={post.media.alt||"Post"}/>:null}<footer>♡ Like　◯ Comment　↻ Repost　➤ Send</footer></article></section>}

function MediaPicker({post,choose,close,canva}){const [query,setQuery]=useState(post.pillar),[results,setResults]=useState([]),[error,setError]=useState("");const search=async e=>{e.preventDefault();const key=localStorage.getItem("signal-unsplash-key");if(!key)return setError("Add your Unsplash Access Key below.");const r=await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=12`,{headers:{Authorization:`Client-ID ${key}`}});const data=await r.json();if(!r.ok)return setError(data.errors?.[0]||"Search failed");setResults(data.results.map(x=>({id:x.id,url:x.urls.regular,thumb:x.urls.small,alt:x.alt_description||query,credit:x.user.name,source:"Unsplash",downloadLocation:x.links.download_location})));setError("")};return <div className="modal"><section><header><div><h2>Choose a post image</h2><p>Search Unsplash or continue in Canva.</p></div><button onClick={close}>✕</button></header><form onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Unsplash"/><button className="primary">Search</button></form><label className="key">Unsplash Access Key<input type="password" defaultValue={localStorage.getItem("signal-unsplash-key")||""} onChange={e=>localStorage.setItem("signal-unsplash-key",e.target.value)}/></label>{error?<p className="error">{error}</p>:null}<div className="mediaresults">{results.map(x=><button key={x.id} onClick={()=>choose(x)}><img src={x.thumb}/><span>Photo by {x.credit}</span></button>)}</div><button className="canva" onClick={canva}>Create in Canva ↗</button></section></div>}
function Settings({notify}){const erase=async()=>{if(!confirm("Delete PostingSignal account data?"))return;await fetch(`${API}/api/account`,{method:"DELETE"});localStorage.removeItem("signal-posts");localStorage.removeItem("signal-unsplash-key");notify("Account data deleted")};return <div className="settings"><h1>Account and data</h1><p>PostingSignal stores post content in this browser. Canva credentials remain on the local API server.</p><section><h2>Delete account</h2><p>Permanently remove saved posts, the Unsplash key, Canva connection, uploaded documents, and generated images.</p><button className="danger" onClick={erase}>Delete my account</button></section></div>}
