"use client";

import React, { useEffect, useMemo, useState } from "react";
import { UserButton, useUser } from "@clerk/nextjs";

const API = "";
const PILLARS = ["AI readiness", "Finance transformation", "Trusted data", "Executive decision-making"];
const NAV = ["Pulse", "Calendar", "Ideas", "Drafts", "Library", "Analytics", "Brand Profile", "Settings"];
const TYPES = ["Standard post", "Event", "Celebrate", "Hiring", "Poll", "Document", "Find an expert"];
const seed = [
  {id:1,date:"2026-07-20",title:"Why AI readiness starts with trusted data",summary:"AI pilots fail when data cannot be trusted. Here is the foundation I help organizations build.",pillar:"AI readiness",stage:"Review",hook:"AI readiness does not begin with a model. It begins with data leaders can trust.",body:"The organizations moving fastest with AI are not skipping governance. They are investing in it.\n\nA trusted data foundation means shared definitions, clear ownership, reliable pipelines, and controls that make quality visible.",closing:"Where is the biggest trust gap in your organization’s data today?"},
  {id:2,date:"2026-07-22",title:"From five days to three hours: redesigning executive reporting",summary:"How we cut monthly reporting from five days to under three hours—and what it unlocked.",pillar:"Finance transformation",stage:"Draft",hook:"We cut monthly executive reporting from five days to under three hours. Here is what changed.",body:"The breakthrough was not a new tool—it was a new design.\n\nWe standardized data definitions, automated collection and validation, and rebuilt the report layer around clarity and decision value.",closing:"What is one report your team could redesign this quarter?"},
  {id:3,date:"2026-07-24",title:"The hidden cost of KPI disagreement",summary:"When KPIs do not agree, decisions slow down.",pillar:"Trusted data",stage:"Idea",hook:"",body:"",closing:""},
  {id:4,date:"2026-07-27",title:"What Finance should ask before automating a process",summary:"Automation without the right questions just automates waste.",pillar:"Finance transformation",stage:"Idea",hook:"",body:"",closing:""},
  {id:5,date:"2026-07-29",title:"Data integrity is not a tech problem—it is a leadership decision",summary:"How strong data governance drives better insight and builds executive trust.",pillar:"Trusted data",stage:"Review",hook:"",body:"",closing:""},
  {id:6,date:"2026-07-31",title:"From insight to action: the executive reporting chain",summary:"A simple model to connect data, insight, decision and outcome.",pillar:"Executive decision-making",stage:"Draft",hook:"",body:"",closing:""},
  {id:7,date:"2026-08-03",title:"Three questions every CFO should ask about AI",summary:"A short checklist to separate signal from noise in AI initiatives.",pillar:"AI readiness",stage:"Approved",hook:"Before approving another AI pilot, ask three questions.",body:"Is the underlying data trusted? Is the business decision clear? Is there an accountable owner for the outcome?",closing:"Which question is most often missing from the conversation?"}
];
const pulseSeed = [
  {id:"onn-1",headline:"CFOs push for real-time data as boards demand faster decisions",summary:"Finance leaders are accelerating investment in real-time reporting and integrated data platforms to reduce decision latency.",topic:"Finance transformation",trend:"up",potential:"High",readTime:4,image:"/pulse-architecture.png"},
  {id:"onn-2",headline:"Data quality is now the #1 risk to AI initiatives",summary:"Poor data quality and governance remain the leading barriers to scaling AI and automation across the enterprise.",topic:"Trusted data",trend:"up",potential:"High",readTime:5,image:"/pulse-data-center.png"},
  {id:"onn-3",headline:"Automating the close: where finance teams see the biggest gains",summary:"From reconciliations to reporting, finance teams are finding measurable time savings without sacrificing control.",topic:"Finance transformation",trend:"up",potential:"Medium",readTime:6},
  {id:"onn-4",headline:"New privacy rules raise the stakes for finance data",summary:"Upcoming regulations will require stricter controls over how financial data is collected, stored, and shared.",topic:"Trusted data",trend:"flat",potential:"Medium",readTime:4},
  {id:"onn-5",headline:"How leading CFOs are building influence beyond the numbers",summary:"Finance leaders are using trusted insight to shape strategy, drive value, and earn a stronger seat at the table.",topic:"Executive decision-making",trend:"up",potential:"High",readTime:7},
  {id:"onn-6",headline:"The cloud cost dilemma: spend smarter, not just less",summary:"Organizations are shifting from blunt cost reduction to clearer ownership, visibility, and outcome-based cloud investment.",topic:"AI readiness",trend:"down",potential:"Medium",readTime:5}
];
const count = (value="") => [...value].length;
const postText = p => [p.title,p.hook,p.body,p.closing].filter(Boolean).join("\n\n");
const formatDate = d => new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));
const formatTime = time => new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(`2000-01-01T${time||"09:00"}:00`));
const localTimezone = () => Intl.DateTimeFormat().resolvedOptions().timeZone || "America/New_York";
const postPayload = post => {
  const {id,title,summary,hook,body,closing,pillar,stage,date,time,timezone,publishingJob,scheduledFor,createdAt,updatedAt,publishedAt,linkedinPostId,...content}=post;
  return {title:title||"Untitled post",summary:summary||"",hook:hook||"",body:body||"",closing:closing||"",pillar:pillar||PILLARS[0],stage:stage||"Idea",date,time:time||"09:00",timezone:timezone||localTimezone(),content};
};
const scheduledInstant = post => new Date(`${post.date}T${post.time||"09:00"}:00`).toISOString();

export default function PostingSignalApp(){
  const [posts,setPosts]=useState(seed),[hydrated,setHydrated]=useState(false);
  const [active,setActive]=useState("Pulse"),[selected,setSelected]=useState(2),[editing,setEditing]=useState(false),[toast,setToast]=useState(""),[mediaOpen,setMediaOpen]=useState(false),[savedArticles,setSavedArticles]=useState([]),[hiddenArticles,setHiddenArticles]=useState([]);
  useEffect(()=>{const controller=new AbortController();const load=async()=>{let localPosts=seed;try{localPosts=JSON.parse(localStorage.getItem("signal-posts"))||seed}catch{}try{const response=await fetch("/api/posts",{signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||"Posts could not be loaded");let durablePosts=data.posts||[];if(!durablePosts.length&&localPosts.length){const imported=await fetch("/api/posts/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({posts:localPosts})});const importedData=await imported.json();if(imported.ok)durablePosts=importedData.posts||[]}const next=durablePosts.length?durablePosts:localPosts;setPosts(next);setSelected(next[0]?.id||null);setSavedArticles(next.filter(post=>post.sourceArticleId&&post.stage==="Idea").map(post=>post.sourceArticleId))}catch(error){if(!controller.signal.aborted){setPosts(localPosts);setToast(error instanceof Error?error.message:"Using browser posts until the database is available")}}finally{if(!controller.signal.aborted)setHydrated(true)}};load();return()=>controller.abort()},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("signal-posts",JSON.stringify(posts))},[posts,hydrated]);
  const post=posts.find(p=>p.id===selected)||posts[0];
  const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)};
  const patch=(key,value)=>setPosts(all=>all.map(p=>p.id===selected?{...p,[key]:value}:p));
  const savePost=async next=>{const response=await fetch(`/api/posts/${next.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(next))});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be saved");setPosts(all=>all.map(item=>item.id===next.id?data.post:item));return data.post};
  const schedulePost=async next=>{const response=await fetch(`/api/posts/${next.id}/schedule`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scheduledFor:scheduledInstant(next),date:next.date,time:next.time||"09:00",timezone:next.timezone||localTimezone()})});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be scheduled");setPosts(all=>all.map(item=>item.id===next.id?data.post:item));return data.post};
  const movePost=async(id,date)=>{const current=posts.find(item=>item.id===id);if(!current)return;const next={...current,date,updatedAt:new Date().toISOString()};setPosts(all=>all.map(item=>item.id===id?next:item));try{if(current.stage==="Scheduled")await schedulePost(next);else await savePost(next);notify(`Post moved to ${formatDate(date)}`)}catch(error){notify(error instanceof Error?error.message:"Post could not be moved")}};
  const openPost=id=>{setSelected(id);setEditing(true)};
  const saveArticle=async article=>{const existing=posts.find(item=>item.sourceArticleId===article.id&&item.stage==="Idea");if(existing){try{const response=await fetch(`/api/posts/${existing.id}`,{method:"DELETE"});if(!response.ok)throw Error("Saved idea could not be removed");setPosts(all=>all.filter(item=>item.id!==existing.id));setSavedArticles(all=>all.filter(id=>id!==article.id));notify("Removed from Ideas")}catch(error){notify(error instanceof Error?error.message:"Saved idea could not be removed")}return}const draft={date:new Date().toISOString().slice(0,10),time:"09:00",timezone:localTimezone(),title:article.headline,summary:article.summary,pillar:article.topic,stage:"Idea",hook:"",body:"",closing:"",sourceArticleId:article.id,source:"ONN"};try{const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(draft))});const data=await response.json();if(!response.ok)throw Error(data.error||"Article could not be saved");setPosts(all=>[data.post,...all]);setSavedArticles(all=>[...all,article.id]);notify("Saved to Ideas")}catch(error){notify(error instanceof Error?error.message:"Article could not be saved")}};
  const draftArticle=async article=>{let draft=posts.find(item=>item.sourceArticleId===article.id&&["Draft","Review"].includes(item.stage));if(!draft){const next={date:new Date().toISOString().slice(0,10),time:"09:00",timezone:localTimezone(),title:article.headline,summary:article.summary,pillar:article.topic,stage:"Draft",hook:article.headline,body:article.summary,closing:"What is your perspective?",sourceArticleId:article.id,source:"ONN"};try{const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(next))});const data=await response.json();if(!response.ok)throw Error(data.error||"Draft could not be created");draft=data.post;setPosts(all=>[draft,...all])}catch(error){notify(error instanceof Error?error.message:"Draft could not be created");return}}setSelected(draft.id);setActive("Drafts");setEditing(true)};
  const create=async(stage="Idea",date=new Date().toISOString().slice(0,10))=>{const draft={date,time:"09:00",timezone:localTimezone(),title:stage==="Idea"?"Untitled idea":"Untitled post",summary:"Add a short premise.",pillar:PILLARS[0],stage,hook:"",body:"",closing:""};try{const response=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(postPayload(draft))});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be created");setPosts(v=>[data.post,...v]);setSelected(data.post.id);setEditing(true)}catch(error){notify(error instanceof Error?error.message:"Post could not be created")}};
  const saveStage=async(stage,message)=>{const next={...post,stage,updatedAt:new Date().toISOString()};setPosts(all=>all.map(item=>item.id===selected?next:item));try{await savePost(next);notify(message)}catch(error){notify(error instanceof Error?error.message:"Post could not be saved")}};
  const approve=async()=>{const next={...post,stage:"Scheduled",time:post.time||"09:00",timezone:post.timezone||localTimezone()};try{await savePost({...next,stage:"Approved"});await schedulePost(next);notify(`Approved and scheduled for ${formatDate(next.date)} at ${next.time}`)}catch(error){notify(error instanceof Error?error.message:"Post could not be scheduled")}};
  const remove=async()=>{if(!confirm(`Delete “${post.title}”? This cannot be undone.`))return;try{const response=await fetch(`/api/posts/${post.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw Error(data.error||"Post could not be deleted");setPosts(v=>v.filter(p=>p.id!==selected));setEditing(false);notify("Post deleted")}catch(error){notify(error instanceof Error?error.message:"Post could not be deleted")}};
  const postNow=async()=>{if(!confirm(`Publish “${post.title}” to your connected LinkedIn account now?`))return;try{const response=await fetch("/api/linkedin/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:postText(post),idempotencyKey:`post-${post.id}-${post.updatedAt||post.date}`})});const data=await response.json();if(!response.ok)throw Error(data.error||"LinkedIn publishing failed");const next={...post,stage:"Published",publishedAt:new Date().toISOString(),linkedinPostId:data.platformPostId};setPosts(all=>all.map(item=>item.id===post.id?next:item));await savePost(next);notify("Published to LinkedIn")}catch(error){notify(error instanceof Error?error.message:"LinkedIn publishing failed")}};
  const openCanva=async()=>{const popup=window.open("about:blank","posting-signal-canva");try{const response=await fetch(`${API}/api/canva/launch`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({postId:post.id,title:post.title,imageUrl:post.media?.url})});const data=await response.json();if(!response.ok)throw Error(data.error||"Canva could not start");popup.location=data.launchUrl}catch(error){popup?.close();notify(error.message)}};
  useEffect(()=>{const q=new URLSearchParams(location.search),designId=q.get("canvaDesignId"),postId=q.get("canvaPostId");if(!designId||!postId)return;fetch(`${API}/api/canva/export`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({designId,postId})}).then(r=>r.json()).then(data=>setPosts(all=>all.map(p=>String(p.id)===postId?{...p,media:{url:data.url,alt:`Canva design for ${p.title}`,source:"Canva",designId}}:p))).finally(()=>history.replaceState({},"",location.pathname))},[]);
  const composer=editing&&post?<Composer post={post} patch={patch} back={()=>setEditing(false)} browse={()=>setMediaOpen(true)} canva={openCanva} saveIdea={()=>saveStage("Idea","Idea saved")} saveDraft={()=>saveStage("Draft","Draft saved")} approve={approve} remove={remove} postNow={postNow} notify={notify}/>:null;
  return <div className="shell">
    <Sidebar active={active} onNav={n=>{setActive(n);setEditing(false)}}/>
    <main className={editing&&active!=="Calendar"?"editing":""}>
      {editing&&active!=="Calendar"?composer:active==="Pulse"?<Pulse articles={pulseSeed.filter(article=>!hiddenArticles.includes(article.id))} saved={savedArticles} onSave={saveArticle} onDraft={draftArticle} onHide={id=>{setHiddenArticles(all=>[...all,id]);notify("Article hidden")}} notify={notify}/>:active==="Analytics"?<Analytics posts={posts}/>:active==="Brand Profile"?<BrandProfile notify={notify}/>:active==="Settings"?<Settings notify={notify}/>:<Workspace active={active} posts={posts} open={openPost} create={create} movePost={movePost} calendarEditor={editing?composer:null} closeCalendarEditor={()=>setEditing(false)}/>}
      {toast?<div className="toast">{toast}</div>:null}
    </main>
    {mediaOpen&&post?<MediaPicker post={post} choose={m=>{patch("media",m);setMediaOpen(false);notify("Image added")}} close={()=>setMediaOpen(false)} canva={openCanva}/>:null}
  </div>
}

function Icon({name,size=20}){const paths={Pulse:<><path d="M3 12h3l2.1-6 3.3 12 2.4-7 1.7 3H21"/></>,Calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/></>,Ideas:<path d="M12 3 21 12 12 21 3 12Z"/>,Drafts:<><path d="m4 20 4.5-1 10.8-10.8a2.1 2.1 0 0 0-3-3L5.5 16Z"/><path d="m14.8 6.7 3 3"/></>,Library:<><rect x="5" y="5" width="15" height="16" rx="1"/><path d="M3 18V4a1 1 0 0 1 1-1h13"/></>,Analytics:<><path d="M4 20v-7h4v7M10 20V8h4v12M16 20V3h4v17"/></>,"Brand Profile":<><circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,Settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/></>,More:<><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></>,Save:<path d="M6 3h12a1 1 0 0 1 1 1v17l-7-4-7 4V4a1 1 0 0 1 1-1Z"/>,Source:<><path d="M14 3h7v7M10 14 21 3"/><path d="M21 14v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h6"/></>,Share:<><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/></>,Hide:<><path d="M3 3 21 21"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 4.2A10.5 10.5 0 0 1 12 4c5.5 0 9 8 9 8a18 18 0 0 1-2 3.2M6.6 6.6C4.2 8.2 3 12 3 12s3.5 8 9 8a9 9 0 0 0 4-.9"/></>};return <svg className="ui-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

function Sidebar({active,onNav}){const {user}=useUser();const [moreOpen,setMoreOpen]=useState(false);const name=user?.fullName||user?.primaryEmailAddress?.emailAddress||"PostingSignal user";const primary=["Pulse","Calendar","Ideas","Drafts"],secondary=["Library","Analytics","Brand Profile","Settings"];const navigate=name=>{onNav(name);setMoreOpen(false)};return <><aside className="sidebar"><div className="brand"><i className="orbit-mark"/>PostingSignal</div><nav>{NAV.map(n=><button key={n} className={active===n?"active":""} onClick={()=>navigate(n)}><Icon name={n}/><span>{n}</span></button>)}</nav><div className="identity"><UserButton/><span>{name}<small>Authenticated workspace</small></span></div></aside><header className="mobile-appbar"><div className="brand"><i className="orbit-mark"/>PostingSignal</div><UserButton/></header>{moreOpen?<div className="mobile-more" role="dialog" aria-label="More navigation"><b>More</b>{secondary.map(n=><button key={n} className={active===n?"active":""} onClick={()=>navigate(n)}><Icon name={n}/>{n}</button>)}</div>:null}<nav className="mobile-nav" aria-label="Primary navigation">{primary.map(n=><button key={n} className={active===n?"active":""} onClick={()=>navigate(n)}><Icon name={n}/><span>{n}</span></button>)}<button className={secondary.includes(active)?"active":""} onClick={()=>setMoreOpen(open=>!open)} aria-expanded={moreOpen}><Icon name="More"/><span>More</span></button></nav></>}

function Workspace({active,posts,open,create,movePost,calendarEditor,closeCalendarEditor}){
  const copy={Calendar:["Calendar","Plan and manage every post"],Ideas:["Ideas","Develop saved signals and original thinking into complete posts."],Drafts:["Drafts in progress","Continue writing, review, and approve active work."],Library:["Content library","Reuse approved posts, images, and documents."]}[active];
  const shown=active==="Ideas"?posts.filter(p=>p.stage==="Idea"):active==="Drafts"?posts.filter(p=>["Draft","Review"].includes(p.stage)):active==="Library"?posts.filter(p=>["Approved","Scheduled","Published","Failed"].includes(p.stage)):posts;
  return <div className={`workspace${active==="Calendar"?" calendar-workspace":""}`}><header><div><h1>{copy[0]}</h1><p>{copy[1]}</p></div>{active!=="Calendar"?<button className="primary" onClick={()=>create(active==="Ideas"?"Idea":active==="Drafts"?"Draft":"Idea")}>＋ {active==="Ideas"?"New Idea":active==="Drafts"?"New draft":"New post"}</button>:null}</header>
  {active==="Calendar"?<PostingCalendar posts={posts} open={open} create={create} movePost={movePost} calendarEditor={calendarEditor} closeCalendarEditor={closeCalendarEditor}/>:<section className="cards">{shown.map(p=><button key={p.id} className="item" onClick={()=>open(p.id)}><time>{formatDate(p.date)}<small>{p.source?`${p.source} signal`:`${p.time||"09:00"} · ${p.timezone||localTimezone()}`}</small></time><span className="itemcopy"><b>{p.title}</b><small>{p.publishingJob?.lastError||p.summary}</small></span><span className="pillar">{p.pillar}</span><span className={`stage ${p.stage.toLowerCase()}`}>{p.stage}</span></button>)}</section>}
  {!shown.length?<div className="empty"><h2>No {active.toLowerCase()} yet</h2><p>Create one to get started.</p></div>:null}</div>
}

function ArticleActions({article,isSaved,onSave,onDraft,onHide,notify,compact=false}){return <div className={`article-actions${compact?" compact":""}`}><button className={isSaved?"saved":""} aria-pressed={isSaved} onClick={()=>onSave(article)}><Icon name="Save"/>{compact?null:isSaved?"Saved":"Save"}</button><button onClick={()=>onDraft(article)}><Icon name="Drafts"/>{compact?null:"Create Draft"}</button><button onClick={()=>notify("ONN source preview opened")}><Icon name="Source"/>{compact?null:"View Source"}</button><button onClick={()=>navigator.clipboard?.writeText(article.headline).then(()=>notify("Article link copied"))}><Icon name="Share"/>{compact?null:"Share"}</button><button onClick={()=>onHide(article.id)}><Icon name="Hide"/>{compact?null:"Hide"}</button></div>}

function SignalMeta({article}){return <div className="article-signal"><b className={article.trend}>{article.trend==="up"?"↗ Trending up":article.trend==="down"?"↘ Trending down":"→ Trending flat"}</b><span>{article.potential} engagement potential</span><small>◷ {article.readTime} min read</small></div>}

function Pulse({articles,saved,onSave,onDraft,onHide,notify}){const [topic,setTopic]=useState("All topics");const shown=topic==="All topics"?articles:articles.filter(article=>article.topic===topic);const lead=shown[0],rest=shown.slice(1);return <div className="pulse editorial-pulse"><header className="pulse-heading"><div><h1>Today’s Pulse</h1><p>Relevant signals from ONN, curated for your voice.</p></div><div className="pulse-controls"><select aria-label="Filter Pulse by topic" value={topic} onChange={event=>setTopic(event.target.value)}><option>All topics</option>{PILLARS.map(pillar=><option key={pillar}>{pillar}</option>)}</select><button className="refresh" onClick={()=>notify("Pulse is up to date")}>↻ <span>Refresh</span></button><small>{shown.length} relevant signals</small></div></header>{lead?<><article className="lead-story"><img src={lead.image||"/pulse-architecture.png"} alt="Contemporary architecture representing real-time finance data"/><div className="lead-copy"><small>ONN　·　{lead.topic}</small><h2>{lead.headline}</h2><p>{lead.summary}</p><SignalMeta article={lead}/><ArticleActions article={lead} isSaved={saved.includes(lead.id)} onSave={onSave} onDraft={onDraft} onHide={onHide} notify={notify}/></div></article><section className="story-index">{rest.map((article,index)=><article className="story-row" key={article.id}>{article.image?<img src={article.image} alt="Enterprise data center"/>:<div className="story-number">0{index+2}</div>}<div className="story-copy"><small>ONN　·　{article.topic}</small><h2>{article.headline}</h2><p>{article.summary}</p></div><SignalMeta article={article}/><ArticleActions compact article={article} isSaved={saved.includes(article.id)} onSave={onSave} onDraft={onDraft} onHide={onHide} notify={notify}/></article>)}</section></>:<div className="empty"><h2>No signals in this topic</h2><p>Choose another topic to continue exploring.</p></div>}</div>}

function Analytics({posts}){const counts={ideas:posts.filter(p=>p.stage==="Idea").length,drafts:posts.filter(p=>["Draft","Review"].includes(p.stage)).length,approved:posts.filter(p=>p.stage==="Approved").length};return <div className="insight-page workspace"><header><div><h1>Analytics</h1><p>Understand your publishing rhythm and what is moving forward.</p></div></header><section className="metric-rail"><article><small>Ideas captured</small><b>{counts.ideas}</b><span>Signals ready to develop</span></article><article><small>Active drafts</small><b>{counts.drafts}</b><span>Posts in progress</span></article><article><small>Approved</small><b>{counts.approved}</b><span>Ready to publish</span></article><article><small>Consistency</small><b>{posts.length?"Strong":"—"}</b><span>Based on your current pipeline</span></article></section><section className="analytics-panel"><div><h2>Content pipeline</h2><p>Your ideas are moving steadily toward publication.</p></div><div className="pipeline-bars">{[["Ideas",counts.ideas],["Drafts",counts.drafts],["Approved",counts.approved]].map(([label,value])=><div key={label}><span>{label}</span><i><b style={{width:`${Math.max(8,Number(value)*18)}%`}}/></i><strong>{value}</strong></div>)}</div></section><p className="future-note">Engagement, reach, clicks, best posting times, and topic performance will appear here as publishing data becomes available.</p></div>}

function BrandProfile({notify}){const [voice,setVoice]=useState("Confident, practical, credible, and human");return <div className="brand-profile workspace"><header><div><h1>Brand Profile</h1><p>Give the Brand Coach a clear foundation for every recommendation.</p></div><button className="primary" onClick={()=>notify("Brand profile saved")}>Save profile</button></header><div className="profile-layout"><section><h2>Voice and positioning</h2><label>Brand voice<textarea rows="3" value={voice} onChange={event=>setVoice(event.target.value)}/></label><label>Primary audience<textarea rows="3" defaultValue="Finance leaders, CFOs, FP&A professionals, and transformation executives"/></label><label>What you want to be known for<textarea rows="4" defaultValue="Practical AI adoption, finance transformation, trusted data, and executive decision-making."/></label></section><aside><h2>Content pillars</h2>{PILLARS.map((pillar,index)=><article key={pillar}><i>{index+1}</i><div><b>{pillar}</b><p>{["Practical AI adoption built on trusted data and governance.","Modernizing finance operations and reporting.","Data quality, governance, and integrity.","Turning insight into confident action."][index]}</p></div></article>)}</aside></div></div>}

const isoDate=(year,month,day)=>`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
function PostingCalendar({posts,open,create,movePost,calendarEditor,closeCalendarEditor}){
  const [month,setMonth]=useState(()=>{const now=new Date();return new Date(now.getFullYear(),now.getMonth(),1)});
  const [openDay,setOpenDay]=useState(null);
  const [draggedId,setDraggedId]=useState(null),[dropDate,setDropDate]=useState(null);
  const year=month.getFullYear(),monthIndex=month.getMonth(),firstDay=new Date(year,monthIndex,1).getDay(),daysInMonth=new Date(year,monthIndex+1,0).getDate();
  const now=new Date(),todayDate=isoDate(now.getFullYear(),now.getMonth(),now.getDate());
  const ideaCount=posts.filter(post=>post.stage==="Idea").length,draftCount=posts.filter(post=>post.stage==="Draft").length,monthCount=posts.filter(post=>post.date.startsWith(`${year}-${String(monthIndex+1).padStart(2,"0")}`)).length;
  const cells=Array.from({length:42},(_,index)=>{const day=index-firstDay+1;return day>=1&&day<=daysInMonth?{day,date:isoDate(year,monthIndex,day)}:null});
  const byDate=useMemo(()=>{const map=new Map();posts.forEach(post=>{const group=map.get(post.date)||[];group.push(post);map.set(post.date,group)});return map},[posts]);
  const dayPosts=openDay?byDate.get(openDay)||[]:[];
  return <>
    <div className="calendar-toolbar"><div className="calendar-period" aria-label="Choose calendar month and year"><div className="period-stepper"><button aria-label="Previous month" onClick={()=>setMonth(new Date(year,monthIndex-1,1))}>‹</button><h2>{month.toLocaleDateString("en-US",{month:"long"})}</h2><button aria-label="Next month" onClick={()=>setMonth(new Date(year,monthIndex+1,1))}>›</button></div><div className="period-stepper"><button aria-label="Previous year" onClick={()=>setMonth(new Date(year-1,monthIndex,1))}>‹</button><h2>{year}</h2><button aria-label="Next year" onClick={()=>setMonth(new Date(year+1,monthIndex,1))}>›</button></div></div><div className="calendar-counts"><b>{ideaCount} Ideas</b><i/> <b>{draftCount} Drafts</b><i/> <span>{monthCount} posts this month</span></div></div>
    <section className="month-calendar" aria-label={`${month.toLocaleDateString("en-US",{month:"long",year:"numeric"})} posting calendar`}>
      <div className="weekday-row">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><b key={day}>{day}</b>)}</div>
      <div className="month-cells">{cells.map((cell,index)=>cell?<article className={`calendar-cell${dropDate===cell.date?" drop-target":""}`} key={cell.date} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move";setDropDate(cell.date)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget))setDropDate(null)}} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData("text/post-id")||draggedId;if(id)movePost(id,cell.date);setDraggedId(null);setDropDate(null)}}><button className={`day-header${cell.date===todayDate?" current-day":""}`} aria-current={cell.date===todayDate?"date":undefined} onClick={()=>setOpenDay(cell.date)}><b>{cell.day}</b><span>{(byDate.get(cell.date)||[]).length?`${(byDate.get(cell.date)||[]).length} post${(byDate.get(cell.date)||[]).length===1?"":"s"}`:"Plan day"}</span></button><div className="day-posts">{(byDate.get(cell.date)||[]).map(post=><button draggable="true" className={`calendar-post ${post.stage.toLowerCase()}${draggedId===post.id?" dragging":""}`} key={post.id} onDragStart={event=>{setDraggedId(post.id);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/post-id",String(post.id))}} onDragEnd={()=>{setDraggedId(null);setDropDate(null)}} onClick={()=>open(post.id)}><b>{post.title}</b><small>{post.stage} · {formatTime(post.time)}</small></button>)}<button className="ghost-post" onClick={()=>create("Idea",cell.date)} aria-label={`Create a new post on ${formatDate(cell.date)}`}><span>＋</span> New post</button></div></article>:<div className="calendar-cell outside" key={`blank-${index}`}/>)}</div>
      {calendarEditor?<div className="calendar-editor-overlay" role="presentation" onClick={closeCalendarEditor}><section className="calendar-editor-window" role="dialog" aria-modal="true" aria-label="Edit calendar post" onClick={event=>event.stopPropagation()}>{calendarEditor}</section></div>:null}
    </section>
    {openDay?<div className="day-overlay" onClick={()=>setOpenDay(null)}><aside className="day-pane" onClick={event=>event.stopPropagation()}><header><div><small>Posting day</small><h2>{new Date(`${openDay}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</h2><p>{dayPosts.length?`${dayPosts.length} scheduled post${dayPosts.length===1?"":"s"}`:"No posts scheduled yet"}</p></div><button aria-label="Close day pane" onClick={()=>setOpenDay(null)}>✕</button></header><button className="primary day-new" onClick={()=>{setOpenDay(null);create("Idea",openDay)}}>＋ New post for this day</button><div className="day-pane-posts">{dayPosts.map(post=><button key={post.id} onClick={()=>{setOpenDay(null);open(post.id)}}><span><b>{post.title}</b><small>{post.pillar} · {post.stage}</small></span><i>{formatTime(post.time)}　›</i></button>)}{!dayPosts.length?<div className="day-empty"><b>This day is open</b><p>Create a post now or close this pane and choose another date.</p></div>:null}</div></aside></div>:null}
  </>
}
function Pillars(){return <section className="pillars"><h2>My content pillars</h2><div>{PILLARS.map((p,i)=><article key={p}><i>{["◉","↗","◇","○"][i]}</i><span><b>{p}</b><small>{["Practical AI adoption built on trusted data and governance.","Modernizing finance operations and reporting.","Data quality, governance, and integrity.","Turning insight into confident action."][i]}</small></span></article>)}</div></section>}

function Composer({post,patch,back,browse,canva,saveIdea,saveDraft,approve,remove,postNow,notify}){
  const kind=post.stage==="Idea"?"idea":["Draft","Review"].includes(post.stage)?"draft":"post",total=count(postText(post)),type=post.type||"Standard post";
  const update=(key,value)=>{if(count(postText({...post,[key]:value}))<=3000)patch(key,value)};
  return <div className="composer"><div className="topbar"><button onClick={back}>← Back to content</button><div>{kind==="idea"?<><button onClick={saveIdea}>Save idea</button><button className="primary" onClick={saveDraft}>Develop into draft</button></>:kind==="draft"?<><button onClick={saveDraft}>Save draft</button><button className="primary" onClick={approve}>Approve &amp; schedule</button></>:<><button onClick={()=>navigator.clipboard.writeText(postText(post)).then(()=>notify("Post copied"))}>Copy post</button><button className="danger" onClick={remove}>Delete post</button><button className="primary" onClick={postNow}>Post now</button></>}</div></div>
  <header className="composerhead"><h1>Edit {kind}</h1><label>Stage<select value={post.stage} onChange={e=>patch("stage",e.target.value)}>{["Idea","Draft","Review","Approved","Scheduled","Published","Failed"].map(x=><option key={x}>{x}</option>)}</select></label><label>Publishing date<input type="date" value={post.date} onChange={e=>patch("date",e.target.value)}/></label><label>Publishing time<input type="time" value={post.time||"09:00"} onChange={e=>patch("time",e.target.value)}/></label><label>Timezone<input value={post.timezone||localTimezone()} readOnly/></label></header>
  <div className="typebar">{TYPES.map(x=><button className={type===x?"active":""} onClick={()=>patch("type",x)} key={x}>{x}</button>)}</div>
  <div className="columns"><section className="fields"><div className="limit"><b>LinkedIn post text</b><span>{total.toLocaleString()} / 3,000 characters</span></div><Field label="Title" value={post.title} onChange={v=>update("title",v)}/><Field label="Hook" value={post.hook} onChange={v=>update("hook",v)}/><Field label="Body" rows={8} value={post.body} onChange={v=>update("body",v)}/><Field label="Closing question" rows={2} value={post.closing} onChange={v=>update("closing",v)}/><TypeFields type={type} post={post} patch={patch}/><Media post={post} browse={browse} canva={canva}/><div className="meta"><label>Content pillar<select value={post.pillar} onChange={e=>patch("pillar",e.target.value)}>{PILLARS.map(x=><option key={x}>{x}</option>)}</select></label><label>Audience<select value={post.audience||"Finance leaders, CFOs, FP&A professionals"} onChange={e=>patch("audience",e.target.value)}><option>Finance leaders, CFOs, FP&A professionals</option><option>Data & technology leaders</option><option>Transformation executives</option></select></label></div><p className="safety">Nothing posts until you choose Approve &amp; schedule. Once approved, the publishing worker will post automatically at the selected time.</p>{post.publishingJob?<p className={`job-state ${post.publishingJob.status}`}><b>Publishing status: {post.publishingJob.status}</b>{post.publishingJob.lastError?<span>{post.publishingJob.lastError}</span>:null}</p>:null}</section><div className="editor-insights"><Preview post={post} type={type}/><BrandCoach post={post} patch={patch} notify={notify}/></div></div></div>
}
function BrandCoach({post,patch,notify}){const suggestions=[{label:"Stronger hook",detail:"Lead with the measurable outcome to increase the stop rate.",apply:()=>patch("hook",post.hook||`The strongest leaders do not wait for perfect data. They make trust visible.`)},{label:"Body / clarity",detail:"Tighten the second paragraph for faster readability.",apply:()=>patch("body",post.body?.replace(/\n\n/g,"\n")||post.summary)},{label:"Closing question",detail:"Make the ask more specific and actionable.",apply:()=>patch("closing","What is one practical step your team could take this quarter?")},{label:"Tone",detail:"Keep the point confident, direct, and constructive."},{label:"Storytelling",detail:"Add one brief moment of context before the lesson."},{label:"Credibility",detail:"Support the argument with a measured outcome."},{label:"Authenticity",detail:"Include a personal observation only you could make."}];return <aside className="brand-coach"><header><div><h2>✦ AI Brand Coach</h2><p>Real-time guidance to strengthen your post.</p></div><span>Optional</span></header><section className="alignment"><div><b>Brand Alignment</b><em>On-brand</em></div><div className="score"><strong>{post.hook&&post.body?92:78}</strong><span>Strong alignment with your voice and content strategy.</span></div><p>Focused on practical outcomes, trusted insight, and executive impact.</p></section><section className="platform-recommendation"><b>Platform Recommendation</b><strong>in　LinkedIn <em>Recommended</em></strong><p>This post is concise, insightful, and tailored to your professional audience.</p></section><section className="suggestions"><b>Personalization Suggestions</b>{suggestions.map(item=><article key={item.label}><div><strong>{item.label}</strong><p>{item.detail}</p></div><button onClick={()=>notify(`${item.label} suggestion reviewed`)}>Review</button>{item.apply?<button onClick={()=>{item.apply();notify(`${item.label} applied`)}}>Apply</button>:null}</article>)}</section><small>AI suggestions are optional. You’re in control.</small></aside>}
function Field({label,value="",rows=3,onChange}){return <label className="field"><span>{label}</span>{rows===1?<input value={value} onChange={e=>onChange(e.target.value)}/>:<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function TypeFields({type,post,patch}){if(type==="Poll"){const n=Number(post.pollOptionCount||2);return <section className="context"><Field label={`Poll question · ${count(post.pollQuestion)} / 140`} value={post.pollQuestion||""} onChange={v=>patch("pollQuestion",v.slice(0,140))}/>{Array.from({length:n},(_,i)=><Field key={i} label={`Poll option ${i+1} · ${count(post[`poll${i}`])} / 30`} value={post[`poll${i}`]||""} onChange={v=>patch(`poll${i}`,v.slice(0,30))}/>)}{n<4?<button onClick={()=>patch("pollOptionCount",n+1)}>＋ Add option</button>:null}</section>};if(type==="Document")return <Document post={post} patch={patch}/>;return null}
function Document({post,patch}){const upload=async e=>{const file=e.target.files?.[0];if(!file||post.document)return;const body=new FormData();body.append("document",file);const r=await fetch(`${API}/api/documents`,{method:"POST",body});const data=await r.json();if(r.ok)patch("document",data)};return <section className="context"><b>Document attachment</b><small>One document · PDF, PPT, PPTX, DOC, or DOCX · 100 MB maximum</small>{post.document?<div className="document"><span>{post.document.name}</span><button onClick={()=>{fetch(`${API}/api/documents/${post.document.id}`,{method:"DELETE"});patch("document",null)}}>Remove</button></div>:<label className="upload">Attach document<input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx" onChange={upload}/></label>}</section>}
function Media({post,browse,canva}){return <section className="media"><div><b>Post image</b><small>{post.media?.source||"Auto-selected recommendation"}</small></div>{post.media?.url?<img src={post.media.url} alt={post.media.alt||"Post"}/>:<div className="imageplaceholder">Image preview</div>}<div><button onClick={browse}>Browse Unsplash</button><button onClick={canva}>Create in Canva ↗</button></div></section>}
function Preview({post,type}){return <section className="preview"><h2>LinkedIn preview</h2><article><header><b>EP</b><span><strong>Earl Powery</strong><small>Enterprise transformation leader</small><small>Now · 🌐</small></span><i>•••</i></header><div className="copy">{[post.title,post.hook,post.body,post.closing].filter(Boolean).map((x,i)=><p className={i===0?"title":""} key={i}>{x}</p>)}</div>{type==="Poll"?<div className="poll"><b>{post.pollQuestion||"What is your perspective?"}</b>{Array.from({length:Number(post.pollOptionCount||2)},(_,i)=><button key={i}>{post[`poll${i}`]||`Option ${i+1}`}</button>)}</div>:post.document?<div className="docpreview">▤ {post.document.name}</div>:post.media?.url?<img src={post.media.url} alt={post.media.alt||"Post"}/>:null}<footer>♡ Like　◯ Comment　↻ Repost　➤ Send</footer></article></section>}

function MediaPicker({post,choose,close,canva}){const [query,setQuery]=useState(post.pillar),[results,setResults]=useState([]),[error,setError]=useState("");const search=async e=>{e.preventDefault();const key=localStorage.getItem("signal-unsplash-key");if(!key)return setError("Add your Unsplash Access Key below.");const r=await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=12`,{headers:{Authorization:`Client-ID ${key}`}});const data=await r.json();if(!r.ok)return setError(data.errors?.[0]||"Search failed");setResults(data.results.map(x=>({id:x.id,url:x.urls.regular,thumb:x.urls.small,alt:x.alt_description||query,credit:x.user.name,source:"Unsplash",downloadLocation:x.links.download_location})));setError("")};return <div className="modal"><section><header><div><h2>Choose a post image</h2><p>Search Unsplash or continue in Canva.</p></div><button onClick={close}>✕</button></header><form onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Unsplash"/><button className="primary">Search</button></form><label className="key">Unsplash Access Key<input type="password" defaultValue={localStorage.getItem("signal-unsplash-key")||""} onChange={e=>localStorage.setItem("signal-unsplash-key",e.target.value)}/></label>{error?<p className="error">{error}</p>:null}<div className="mediaresults">{results.map(x=><button key={x.id} onClick={()=>choose(x)}><img src={x.thumb}/><span>Photo by {x.credit}</span></button>)}</div><button className="canva" onClick={canva}>Create in Canva ↗</button></section></div>}
function LinkedInConnection({notify}){const [status,setStatus]=useState({loading:true,connected:false,connection:null});useEffect(()=>{const controller=new AbortController();const load=async()=>{try{const response=await fetch("/api/linkedin/status",{signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||"Connection status unavailable");setStatus({...data,loading:false})}catch{if(!controller.signal.aborted)setStatus({loading:false,connected:false,connection:null})}};load();return()=>controller.abort()},[]);const disconnect=async()=>{if(!confirm("Disconnect this LinkedIn account?"))return;const response=await fetch("/api/linkedin/status",{method:"DELETE"});if(response.ok){setStatus({loading:false,connected:false,connection:null});notify("LinkedIn disconnected")}else notify("LinkedIn could not be disconnected")};return <section className="connection-card"><div className="connection-heading"><div><h2>LinkedIn publishing</h2><p>{status.loading?"Checking connection…":status.connected?`Connected as ${status.connection?.displayName||"LinkedIn member"}`:"Connect your LinkedIn account to publish approved posts directly."}</p></div><span className={`connection-state ${status.connected?"connected":"disconnected"}`}>{status.loading?"Checking":status.connected?"Connected":"Not connected"}</span></div>{status.connected?<div className="connection-actions"><small>{status.connection?.expiresAt?`Access expires ${new Date(status.connection.expiresAt).toLocaleDateString()}`:"LinkedIn access is active"}</small><button onClick={disconnect}>Disconnect</button></div>:<a className="primary connection-button" href="/api/linkedin/connect">Connect LinkedIn</a>}</section>}
function Settings({notify}){const erase=async()=>{if(!confirm("Delete PostingSignal account data?"))return;await fetch(`${API}/api/account`,{method:"DELETE"});localStorage.removeItem("signal-posts");localStorage.removeItem("signal-unsplash-key");notify("Account data deleted")};return <div className="settings"><h1>Account and integrations</h1><p>Connect the services PostingSignal uses to prepare and publish your content.</p><LinkedInConnection notify={notify}/><section className="danger-zone"><h2>Delete account</h2><p>Permanently remove saved posts, the Unsplash key, Canva connection, uploaded documents, and generated images.</p><button className="danger" onClick={erase}>Delete my account</button></section></div>}
